import { plainToClass } from "class-transformer";
import { Appointment } from '../FhirTsLib/Appointment';
import { Account } from '../FhirTsLib/Account';
import { Invoice } from '../FhirTsLib/Invoice';
import { CatalogEntry } from '../FhirTsLib/CatalogEntry';
import { EventDefinition } from '../FhirTsLib/EventDefinition';
import { DocumentManifest } from '../FhirTsLib/DocumentManifest';
import { MessageDefinition } from '../FhirTsLib/MessageDefinition';
import { Goal } from '../FhirTsLib/Goal';
import { MedicinalProductPackaged } from '../FhirTsLib/MedicinalProductPackaged';
import { Endpoint } from '../FhirTsLib/Endpoint';
import { EnrollmentRequest } from '../FhirTsLib/EnrollmentRequest';
import { Consent } from '../FhirTsLib/Consent';
import { CapabilityStatement } from '../FhirTsLib/CapabilityStatement';
import { Measure } from '../FhirTsLib/Measure';
import { Medication } from '../FhirTsLib/Medication';
import { ResearchSubject } from '../FhirTsLib/ResearchSubject';
import { Subscription } from '../FhirTsLib/Subscription';
import { DocumentReference } from '../FhirTsLib/DocumentReference';
import { GraphDefinition } from '../FhirTsLib/GraphDefinition';
import { Parameters } from '../FhirTsLib/Parameters';
import { CoverageEligibilityResponse } from '../FhirTsLib/CoverageEligibilityResponse';
import { MeasureReport } from '../FhirTsLib/MeasureReport';
import { PractitionerRole } from '../FhirTsLib/PractitionerRole';
import { SubstanceReferenceInformation } from '../FhirTsLib/SubstanceReferenceInformation';
import { RelatedPerson } from '../FhirTsLib/RelatedPerson';
import { ServiceRequest } from '../FhirTsLib/ServiceRequest';
import { SupplyRequest } from '../FhirTsLib/SupplyRequest';
import { Practitioner } from '../FhirTsLib/Practitioner';
import { VerificationResult } from '../FhirTsLib/VerificationResult';
import { SubstanceProtein } from '../FhirTsLib/SubstanceProtein';
import { BodyStructure } from '../FhirTsLib/BodyStructure';
import { Slot } from '../FhirTsLib/Slot';
import { Contract } from '../FhirTsLib/Contract';
import { Person } from '../FhirTsLib/Person';
import { RiskAssessment } from '../FhirTsLib/RiskAssessment';
import { Group } from '../FhirTsLib/Group';
import { PaymentNotice } from '../FhirTsLib/PaymentNotice';
import { ResearchDefinition } from '../FhirTsLib/ResearchDefinition';
import { MedicinalProductManufactured } from '../FhirTsLib/MedicinalProductManufactured';
import { Organization } from '../FhirTsLib/Organization';
import { CareTeam } from '../FhirTsLib/CareTeam';
import { ImplementationGuide } from '../FhirTsLib/ImplementationGuide';
import { ImagingStudy } from '../FhirTsLib/ImagingStudy';
import { FamilyMemberHistory } from '../FhirTsLib/FamilyMemberHistory';
import { ChargeItem } from '../FhirTsLib/ChargeItem';
import { ResearchElementDefinition } from '../FhirTsLib/ResearchElementDefinition';
import { ObservationDefinition } from '../FhirTsLib/ObservationDefinition';
import { Encounter } from '../FhirTsLib/Encounter';
import { Substance } from '../FhirTsLib/Substance';
import { SubstanceSpecification } from '../FhirTsLib/SubstanceSpecification';
import { SearchParameter } from '../FhirTsLib/SearchParameter';
import { ActivityDefinition } from '../FhirTsLib/ActivityDefinition';
import { Communication } from '../FhirTsLib/Communication';
import { InsurancePlan } from '../FhirTsLib/InsurancePlan';
import { Linkage } from '../FhirTsLib/Linkage';
import { SubstanceSourceMaterial } from '../FhirTsLib/SubstanceSourceMaterial';
import { ImmunizationEvaluation } from '../FhirTsLib/ImmunizationEvaluation';
import { DeviceUseStatement } from '../FhirTsLib/DeviceUseStatement';
import { RequestGroup } from '../FhirTsLib/RequestGroup';
import { DeviceRequest } from '../FhirTsLib/DeviceRequest';
import { MessageHeader } from '../FhirTsLib/MessageHeader';
import { ImmunizationRecommendation } from '../FhirTsLib/ImmunizationRecommendation';
import { Provenance } from '../FhirTsLib/Provenance';
import { Task } from '../FhirTsLib/Task';
import { Questionnaire } from '../FhirTsLib/Questionnaire';
import { ExplanationOfBenefit } from '../FhirTsLib/ExplanationOfBenefit';
import { MedicinalProductPharmaceutical } from '../FhirTsLib/MedicinalProductPharmaceutical';
import { ResearchStudy } from '../FhirTsLib/ResearchStudy';
import { Specimen } from '../FhirTsLib/Specimen';
import { AllergyIntolerance } from '../FhirTsLib/AllergyIntolerance';
import { CarePlan } from '../FhirTsLib/CarePlan';
import { StructureDefinition } from '../FhirTsLib/StructureDefinition';
import { ChargeItemDefinition } from '../FhirTsLib/ChargeItemDefinition';
import { EpisodeOfCare } from '../FhirTsLib/EpisodeOfCare';
import { OperationOutcome } from '../FhirTsLib/OperationOutcome';
import { Procedure } from '../FhirTsLib/Procedure';
import { List } from '../FhirTsLib/List';
import { ConceptMap } from '../FhirTsLib/ConceptMap';
import { OperationDefinition } from '../FhirTsLib/OperationDefinition';
import { ValueSet } from '../FhirTsLib/ValueSet';
import { Immunization } from '../FhirTsLib/Immunization';
import { MedicationRequest } from '../FhirTsLib/MedicationRequest';
import { EffectEvidenceSynthesis } from '../FhirTsLib/EffectEvidenceSynthesis';
import { BiologicallyDerivedProduct } from '../FhirTsLib/BiologicallyDerivedProduct';
import { Device } from '../FhirTsLib/Device';
import { VisionPrescription } from '../FhirTsLib/VisionPrescription';
import { Media } from '../FhirTsLib/Media';
import { MedicinalProductContraindication } from '../FhirTsLib/MedicinalProductContraindication';
import { EvidenceVariable } from '../FhirTsLib/EvidenceVariable';
import { MolecularSequence } from '../FhirTsLib/MolecularSequence';
import { MedicinalProduct } from '../FhirTsLib/MedicinalProduct';
import { DeviceMetric } from '../FhirTsLib/DeviceMetric';
import { CodeSystem } from '../FhirTsLib/CodeSystem';
import { Flag } from '../FhirTsLib/Flag';
import { SubstanceNucleicAcid } from '../FhirTsLib/SubstanceNucleicAcid';
import { RiskEvidenceSynthesis } from '../FhirTsLib/RiskEvidenceSynthesis';
import { AppointmentResponse } from '../FhirTsLib/AppointmentResponse';
import { StructureMap } from '../FhirTsLib/StructureMap';
import { AdverseEvent } from '../FhirTsLib/AdverseEvent';
import { GuidanceResponse } from '../FhirTsLib/GuidanceResponse';
import { Observation } from '../FhirTsLib/Observation';
import { MedicationAdministration } from '../FhirTsLib/MedicationAdministration';
import { EnrollmentResponse } from '../FhirTsLib/EnrollmentResponse';
import { Binary } from '../FhirTsLib/Binary';
import { Library } from '../FhirTsLib/Library';
import { MedicinalProductInteraction } from '../FhirTsLib/MedicinalProductInteraction';
import { MedicationStatement } from '../FhirTsLib/MedicationStatement';
import { CommunicationRequest } from '../FhirTsLib/CommunicationRequest';
import { TestScript } from '../FhirTsLib/TestScript';
import { Basic } from '../FhirTsLib/Basic';
import { SubstancePolymer } from '../FhirTsLib/SubstancePolymer';
import { TestReport } from '../FhirTsLib/TestReport';
import { ClaimResponse } from '../FhirTsLib/ClaimResponse';
import { MedicationDispense } from '../FhirTsLib/MedicationDispense';
import { DiagnosticReport } from '../FhirTsLib/DiagnosticReport';
import { OrganizationAffiliation } from '../FhirTsLib/OrganizationAffiliation';
import { HealthcareService } from '../FhirTsLib/HealthcareService';
import { MedicinalProductIndication } from '../FhirTsLib/MedicinalProductIndication';
import { NutritionOrder } from '../FhirTsLib/NutritionOrder';
import { TerminologyCapabilities } from '../FhirTsLib/TerminologyCapabilities';
import { Evidence } from '../FhirTsLib/Evidence';
import { AuditEvent } from '../FhirTsLib/AuditEvent';
import { PaymentReconciliation } from '../FhirTsLib/PaymentReconciliation';
import { Condition } from '../FhirTsLib/Condition';
import { SpecimenDefinition } from '../FhirTsLib/SpecimenDefinition';
import { Composition } from '../FhirTsLib/Composition';
import { DetectedIssue } from '../FhirTsLib/DetectedIssue';
import { Bundle } from '../FhirTsLib/Bundle';
import { CompartmentDefinition } from '../FhirTsLib/CompartmentDefinition';
import { MedicationKnowledge } from '../FhirTsLib/MedicationKnowledge';
import { MedicinalProductIngredient } from '../FhirTsLib/MedicinalProductIngredient';
import { Patient } from '../FhirTsLib/Patient';
import { Coverage } from '../FhirTsLib/Coverage';
import { QuestionnaireResponse } from '../FhirTsLib/QuestionnaireResponse';
import { CoverageEligibilityRequest } from '../FhirTsLib/CoverageEligibilityRequest';
import { NamingSystem } from '../FhirTsLib/NamingSystem';
import { MedicinalProductUndesirableEffect } from '../FhirTsLib/MedicinalProductUndesirableEffect';
import { ExampleScenario } from '../FhirTsLib/ExampleScenario';
import { Schedule } from '../FhirTsLib/Schedule';
import { SupplyDelivery } from '../FhirTsLib/SupplyDelivery';
import { ClinicalImpression } from '../FhirTsLib/ClinicalImpression';
import { DeviceDefinition } from '../FhirTsLib/DeviceDefinition';
import { PlanDefinition } from '../FhirTsLib/PlanDefinition';
import { MedicinalProductAuthorization } from '../FhirTsLib/MedicinalProductAuthorization';
import { Claim } from '../FhirTsLib/Claim';
import { Location } from '../FhirTsLib/Location';

/*
 * This map holds a Resource Type name found in the FHIR object under the
 * field named 'resourceType'.  It always a constant value that identifies
 * a FHIR object.  Not all FHIR objects have this, but those that don't tend
 * to be lower level objects that are always included into other objects.
 * Associated with the Resource type name is the function that performs
 * the conversion for the FHIR object.
*/
export const FHIR_RESOURCE_TYPE_TO_OBJECT = new Map();

FHIR_RESOURCE_TYPE_TO_OBJECT.set('Appointment', (jsonData: string) => { return plainToClass(Appointment, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Account', (jsonData: string) => { return plainToClass(Account, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Invoice', (jsonData: string) => { return plainToClass(Invoice, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('CatalogEntry', (jsonData: string) => { return plainToClass(CatalogEntry, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('EventDefinition', (jsonData: string) => { return plainToClass(EventDefinition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('DocumentManifest', (jsonData: string) => { return plainToClass(DocumentManifest, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MessageDefinition', (jsonData: string) => { return plainToClass(MessageDefinition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Goal', (jsonData: string) => { return plainToClass(Goal, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicinalProductPackaged', (jsonData: string) => { return plainToClass(MedicinalProductPackaged, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Endpoint', (jsonData: string) => { return plainToClass(Endpoint, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('EnrollmentRequest', (jsonData: string) => { return plainToClass(EnrollmentRequest, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Consent', (jsonData: string) => { return plainToClass(Consent, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('CapabilityStatement', (jsonData: string) => { return plainToClass(CapabilityStatement, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Measure', (jsonData: string) => { return plainToClass(Measure, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Medication', (jsonData: string) => { return plainToClass(Medication, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ResearchSubject', (jsonData: string) => { return plainToClass(ResearchSubject, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Subscription', (jsonData: string) => { return plainToClass(Subscription, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('DocumentReference', (jsonData: string) => { return plainToClass(DocumentReference, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('GraphDefinition', (jsonData: string) => { return plainToClass(GraphDefinition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Parameters', (jsonData: string) => { return plainToClass(Parameters, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('CoverageEligibilityResponse', (jsonData: string) => { return plainToClass(CoverageEligibilityResponse, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MeasureReport', (jsonData: string) => { return plainToClass(MeasureReport, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('PractitionerRole', (jsonData: string) => { return plainToClass(PractitionerRole, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('SubstanceReferenceInformation', (jsonData: string) => { return plainToClass(SubstanceReferenceInformation, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('RelatedPerson', (jsonData: string) => { return plainToClass(RelatedPerson, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ServiceRequest', (jsonData: string) => { return plainToClass(ServiceRequest, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('SupplyRequest', (jsonData: string) => { return plainToClass(SupplyRequest, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Practitioner', (jsonData: string) => { return plainToClass(Practitioner, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('VerificationResult', (jsonData: string) => { return plainToClass(VerificationResult, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('SubstanceProtein', (jsonData: string) => { return plainToClass(SubstanceProtein, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('BodyStructure', (jsonData: string) => { return plainToClass(BodyStructure, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Slot', (jsonData: string) => { return plainToClass(Slot, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Contract', (jsonData: string) => { return plainToClass(Contract, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Person', (jsonData: string) => { return plainToClass(Person, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('RiskAssessment', (jsonData: string) => { return plainToClass(RiskAssessment, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Group', (jsonData: string) => { return plainToClass(Group, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('PaymentNotice', (jsonData: string) => { return plainToClass(PaymentNotice, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ResearchDefinition', (jsonData: string) => { return plainToClass(ResearchDefinition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicinalProductManufactured', (jsonData: string) => { return plainToClass(MedicinalProductManufactured, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Organization', (jsonData: string) => { return plainToClass(Organization, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('CareTeam', (jsonData: string) => { return plainToClass(CareTeam, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ImplementationGuide', (jsonData: string) => { return plainToClass(ImplementationGuide, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ImagingStudy', (jsonData: string) => { return plainToClass(ImagingStudy, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('FamilyMemberHistory', (jsonData: string) => { return plainToClass(FamilyMemberHistory, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ChargeItem', (jsonData: string) => { return plainToClass(ChargeItem, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ResearchElementDefinition', (jsonData: string) => { return plainToClass(ResearchElementDefinition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ObservationDefinition', (jsonData: string) => { return plainToClass(ObservationDefinition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Encounter', (jsonData: string) => { return plainToClass(Encounter, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Substance', (jsonData: string) => { return plainToClass(Substance, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('SubstanceSpecification', (jsonData: string) => { return plainToClass(SubstanceSpecification, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('SearchParameter', (jsonData: string) => { return plainToClass(SearchParameter, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ActivityDefinition', (jsonData: string) => { return plainToClass(ActivityDefinition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Communication', (jsonData: string) => { return plainToClass(Communication, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('InsurancePlan', (jsonData: string) => { return plainToClass(InsurancePlan, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Linkage', (jsonData: string) => { return plainToClass(Linkage, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('SubstanceSourceMaterial', (jsonData: string) => { return plainToClass(SubstanceSourceMaterial, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ImmunizationEvaluation', (jsonData: string) => { return plainToClass(ImmunizationEvaluation, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('DeviceUseStatement', (jsonData: string) => { return plainToClass(DeviceUseStatement, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('RequestGroup', (jsonData: string) => { return plainToClass(RequestGroup, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('DeviceRequest', (jsonData: string) => { return plainToClass(DeviceRequest, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MessageHeader', (jsonData: string) => { return plainToClass(MessageHeader, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ImmunizationRecommendation', (jsonData: string) => { return plainToClass(ImmunizationRecommendation, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Provenance', (jsonData: string) => { return plainToClass(Provenance, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Task', (jsonData: string) => { return plainToClass(Task, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Questionnaire', (jsonData: string) => { return plainToClass(Questionnaire, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ExplanationOfBenefit', (jsonData: string) => { return plainToClass(ExplanationOfBenefit, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicinalProductPharmaceutical', (jsonData: string) => { return plainToClass(MedicinalProductPharmaceutical, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ResearchStudy', (jsonData: string) => { return plainToClass(ResearchStudy, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Specimen', (jsonData: string) => { return plainToClass(Specimen, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('AllergyIntolerance', (jsonData: string) => { return plainToClass(AllergyIntolerance, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('CarePlan', (jsonData: string) => { return plainToClass(CarePlan, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('StructureDefinition', (jsonData: string) => { return plainToClass(StructureDefinition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ChargeItemDefinition', (jsonData: string) => { return plainToClass(ChargeItemDefinition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('EpisodeOfCare', (jsonData: string) => { return plainToClass(EpisodeOfCare, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('OperationOutcome', (jsonData: string) => { return plainToClass(OperationOutcome, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Procedure', (jsonData: string) => { return plainToClass(Procedure, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('List', (jsonData: string) => { return plainToClass(List, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ConceptMap', (jsonData: string) => { return plainToClass(ConceptMap, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('OperationDefinition', (jsonData: string) => { return plainToClass(OperationDefinition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ValueSet', (jsonData: string) => { return plainToClass(ValueSet, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Immunization', (jsonData: string) => { return plainToClass(Immunization, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicationRequest', (jsonData: string) => { return plainToClass(MedicationRequest, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('EffectEvidenceSynthesis', (jsonData: string) => { return plainToClass(EffectEvidenceSynthesis, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('BiologicallyDerivedProduct', (jsonData: string) => { return plainToClass(BiologicallyDerivedProduct, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Device', (jsonData: string) => { return plainToClass(Device, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('VisionPrescription', (jsonData: string) => { return plainToClass(VisionPrescription, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Media', (jsonData: string) => { return plainToClass(Media, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicinalProductContraindication', (jsonData: string) => { return plainToClass(MedicinalProductContraindication, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('EvidenceVariable', (jsonData: string) => { return plainToClass(EvidenceVariable, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MolecularSequence', (jsonData: string) => { return plainToClass(MolecularSequence, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicinalProduct', (jsonData: string) => { return plainToClass(MedicinalProduct, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('DeviceMetric', (jsonData: string) => { return plainToClass(DeviceMetric, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('CodeSystem', (jsonData: string) => { return plainToClass(CodeSystem, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Flag', (jsonData: string) => { return plainToClass(Flag, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('SubstanceNucleicAcid', (jsonData: string) => { return plainToClass(SubstanceNucleicAcid, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('RiskEvidenceSynthesis', (jsonData: string) => { return plainToClass(RiskEvidenceSynthesis, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('AppointmentResponse', (jsonData: string) => { return plainToClass(AppointmentResponse, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('StructureMap', (jsonData: string) => { return plainToClass(StructureMap, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('AdverseEvent', (jsonData: string) => { return plainToClass(AdverseEvent, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('GuidanceResponse', (jsonData: string) => { return plainToClass(GuidanceResponse, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Observation', (jsonData: string) => { return plainToClass(Observation, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicationAdministration', (jsonData: string) => { return plainToClass(MedicationAdministration, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('EnrollmentResponse', (jsonData: string) => { return plainToClass(EnrollmentResponse, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Binary', (jsonData: string) => { return plainToClass(Binary, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Library', (jsonData: string) => { return plainToClass(Library, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicinalProductInteraction', (jsonData: string) => { return plainToClass(MedicinalProductInteraction, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicationStatement', (jsonData: string) => { return plainToClass(MedicationStatement, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('CommunicationRequest', (jsonData: string) => { return plainToClass(CommunicationRequest, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('TestScript', (jsonData: string) => { return plainToClass(TestScript, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Basic', (jsonData: string) => { return plainToClass(Basic, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('SubstancePolymer', (jsonData: string) => { return plainToClass(SubstancePolymer, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('TestReport', (jsonData: string) => { return plainToClass(TestReport, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ClaimResponse', (jsonData: string) => { return plainToClass(ClaimResponse, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicationDispense', (jsonData: string) => { return plainToClass(MedicationDispense, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('DiagnosticReport', (jsonData: string) => { return plainToClass(DiagnosticReport, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('OrganizationAffiliation', (jsonData: string) => { return plainToClass(OrganizationAffiliation, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('HealthcareService', (jsonData: string) => { return plainToClass(HealthcareService, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicinalProductIndication', (jsonData: string) => { return plainToClass(MedicinalProductIndication, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('NutritionOrder', (jsonData: string) => { return plainToClass(NutritionOrder, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('TerminologyCapabilities', (jsonData: string) => { return plainToClass(TerminologyCapabilities, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Evidence', (jsonData: string) => { return plainToClass(Evidence, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('AuditEvent', (jsonData: string) => { return plainToClass(AuditEvent, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('PaymentReconciliation', (jsonData: string) => { return plainToClass(PaymentReconciliation, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Condition', (jsonData: string) => { return plainToClass(Condition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('SpecimenDefinition', (jsonData: string) => { return plainToClass(SpecimenDefinition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Composition', (jsonData: string) => { return plainToClass(Composition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('DetectedIssue', (jsonData: string) => { return plainToClass(DetectedIssue, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Bundle', (jsonData: string) => { return plainToClass(Bundle, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('CompartmentDefinition', (jsonData: string) => { return plainToClass(CompartmentDefinition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicationKnowledge', (jsonData: string) => { return plainToClass(MedicationKnowledge, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicinalProductIngredient', (jsonData: string) => { return plainToClass(MedicinalProductIngredient, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Patient', (jsonData: string) => { return plainToClass(Patient, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Coverage', (jsonData: string) => { return plainToClass(Coverage, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('QuestionnaireResponse', (jsonData: string) => { return plainToClass(QuestionnaireResponse, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('CoverageEligibilityRequest', (jsonData: string) => { return plainToClass(CoverageEligibilityRequest, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('NamingSystem', (jsonData: string) => { return plainToClass(NamingSystem, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicinalProductUndesirableEffect', (jsonData: string) => { return plainToClass(MedicinalProductUndesirableEffect, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ExampleScenario', (jsonData: string) => { return plainToClass(ExampleScenario, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Schedule', (jsonData: string) => { return plainToClass(Schedule, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('SupplyDelivery', (jsonData: string) => { return plainToClass(SupplyDelivery, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('ClinicalImpression', (jsonData: string) => { return plainToClass(ClinicalImpression, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('DeviceDefinition', (jsonData: string) => { return plainToClass(DeviceDefinition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('PlanDefinition', (jsonData: string) => { return plainToClass(PlanDefinition, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('MedicinalProductAuthorization', (jsonData: string) => { return plainToClass(MedicinalProductAuthorization, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Claim', (jsonData: string) => { return plainToClass(Claim, JSON.parse(jsonData)); } );
FHIR_RESOURCE_TYPE_TO_OBJECT.set('Location', (jsonData: string) => { return plainToClass(Location, JSON.parse(jsonData)); } );
