import { getValidValueIdx } from '../FhirTsLibValidation/FhirUtils';
import { Type } from 'class-transformer';
import { REGEX_ID, REGEX_VALUE } from '../FhirTsLibValidation/FhirRegex';
import { Element, Extension, Period } from './FhirType';
import { ContactPointSystem_list_ValidValues, ContactPointUse_list_ValidValues } from '../FhirTsLibValidation/Fhir_ValidValues';



/**
 * Details for all kinds of technology mediated contact points for a person or organization, including
 * telephone, email, etc.
 *
 * Generated by Gallaware, Inc. from:
 *    file:/Users/admin/Documents/DevNetbeans/jsonSchemaToJava/target/classes/schema/fhir.schema.json#/definitions/ContactPoint
 */
export class ContactPoint {
  /**
   * A sequence of Unicode characters
   * Field access restricted because there are specific valid values.
   */
  protected id?: string;

  /**
   * May be used to represent additional information that is not part of the basic definition of the
   * element. To make the use of extensions safe and manageable, there is a strict set of governance
   * applied to the definition and use of extensions. Though any implementer can define an extension,
   * there is a set of requirements that SHALL be met as part of the definition of the extension.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Extension)
  protected extension?: Extension[];

  /**
   * Telecommunications form for contact point - what communications system is required to make use of
   * the contact.
   * Field access restricted because there are specific valid values.
   */
  protected system?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _system?: Element;

  /**
   * A sequence of Unicode characters
   * Field access restricted because there are specific valid values.
   */
  protected value?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _value?: Element;

  /**
   * Identifies the purpose for the contact point.
   * Field access restricted because there are specific valid values.
   */
  protected use?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _use?: Element;

  /**
   * An integer with a value that is positive (e.g. >0)
   */
   rank?: number;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _rank?: Element;

  /**
   * A time period defined by a start and end date and optionally time.
   */
  @Type(() => Period)
   period?: Period;


  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setId(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.id) !== 'undefined') {
         delete this.id;
      }
      return;
    }
    
    if (REGEX_ID.test(newValue)) {
      this.id = newValue
    } else {
      throw new Error("Invalid value pattern for id of " + newValue);
    }
  }
  
  public getIdPattern(): string {
    return REGEX_ID.source;
  }
  

  public getId(): string | undefined {
      return this.id;
  }

  public addExtension(newValue: Extension) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.extension) !== 'undefined') {
         delete this.extension;
      }
      return;
    }
    
    if (typeof(this.extension) === 'undefined') {
      this.extension =  [];
    }
    this.extension.push(newValue);
  }

  public getExtension(): Extension[] | undefined {
      return this.extension;
  }

  /*
  * This sets the data ensuring that the value is valid.  If not valid, it throws an error
  * that should be caught.
  */
  public setSystem(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.system) !== 'undefined') {
         delete this.system;
      }
      return;
    }
    
    const idx = getValidValueIdx(ContactPointSystem_list_ValidValues, newValue);
    if (idx >= 0) {
      this.system = ContactPointSystem_list_ValidValues[idx];
    } else {
      throw new Error("Unknown system of " + newValue);
    }
  }
  
  public getContactPointSystemValidValues(): string[] {
    return ContactPointSystem_list_ValidValues;
  }
  

  public getSystem(): string | undefined {
      return this.system;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setValue(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.value) !== 'undefined') {
         delete this.value;
      }
      return;
    }
    
    if (REGEX_VALUE.test(newValue)) {
      this.value = newValue
    } else {
      throw new Error("Invalid value pattern for value of " + newValue);
    }
  }
  
  public getValuePattern(): string {
    return REGEX_VALUE.source;
  }
  

  public getValue(): string | undefined {
      return this.value;
  }

  /*
  * This sets the data ensuring that the value is valid.  If not valid, it throws an error
  * that should be caught.
  */
  public setUse(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.use) !== 'undefined') {
         delete this.use;
      }
      return;
    }
    
    const idx = getValidValueIdx(ContactPointUse_list_ValidValues, newValue);
    if (idx >= 0) {
      this.use = ContactPointUse_list_ValidValues[idx];
    } else {
      throw new Error("Unknown use of " + newValue);
    }
  }
  
  public getContactPointUseValidValues(): string[] {
    return ContactPointUse_list_ValidValues;
  }
  

  public getUse(): string | undefined {
      return this.use;
  }


}


