import { getValidValueIdx } from '../FhirTsLibValidation/FhirUtils';
import { Type } from 'class-transformer';
import { REGEX_ID_000, REGEX_IMPLICITRULES, REGEX_LANGUAGE, REGEX_DISTINCTIDENTIFIER, REGEX_MANUFACTURER, REGEX_MANUFACTUREDATE, REGEX_EXPIRATIONDATE, REGEX_LOTNUMBER, REGEX_SERIALNUMBER, REGEX_MODELNUMBER, REGEX_PARTNUMBER, REGEX_URL } from '../FhirTsLibValidation/FhirRegex';
import { Annotation, CodeableConcept, ContactPoint, DeviceDeviceName, DeviceProperty, DeviceSpecialization, DeviceUdiCarrier, DeviceVersion, Element, Extension, Identifier, Meta, Narrative, Reference, ResourceList, Account, ActivityDefinition, AdverseEvent, AllergyIntolerance, Appointment, AppointmentResponse, AuditEvent, Basic, Binary, BiologicallyDerivedProduct, BodyStructure, Bundle, CapabilityStatement, CarePlan, CareTeam, CatalogEntry, ChargeItem, ChargeItemDefinition, Claim, ClaimResponse, ClinicalImpression, CodeSystem, Communication, CommunicationRequest, CompartmentDefinition, Composition, ConceptMap, Condition, Consent, Contract, Coverage, CoverageEligibilityRequest, CoverageEligibilityResponse, DetectedIssue, DeviceDefinition, DeviceMetric, DeviceRequest, DeviceUseStatement, DiagnosticReport, DocumentManifest, DocumentReference, EffectEvidenceSynthesis, Encounter, Endpoint, EnrollmentRequest, EnrollmentResponse, EpisodeOfCare, EventDefinition, Evidence, EvidenceVariable, ExampleScenario, ExplanationOfBenefit, FamilyMemberHistory, Flag, Goal, GraphDefinition, Group, GuidanceResponse, HealthcareService, ImagingStudy, Immunization, ImmunizationEvaluation, ImmunizationRecommendation, ImplementationGuide, InsurancePlan, Invoice, Library, Linkage, List, Location, Measure, MeasureReport, Media, Medication, MedicationAdministration, MedicationDispense, MedicationKnowledge, MedicationRequest, MedicationStatement, MedicinalProduct, MedicinalProductAuthorization, MedicinalProductContraindication, MedicinalProductIndication, MedicinalProductIngredient, MedicinalProductInteraction, MedicinalProductManufactured, MedicinalProductPackaged, MedicinalProductPharmaceutical, MedicinalProductUndesirableEffect, MessageDefinition, MessageHeader, MolecularSequence, NamingSystem, NutritionOrder, Observation, ObservationDefinition, OperationDefinition, OperationOutcome, Organization, OrganizationAffiliation, Parameters, Patient, PaymentNotice, PaymentReconciliation, Person, PlanDefinition, Practitioner, PractitionerRole, Procedure, Provenance, Questionnaire, QuestionnaireResponse, RelatedPerson, RequestGroup, ResearchDefinition, ResearchElementDefinition, ResearchStudy, ResearchSubject, RiskAssessment, RiskEvidenceSynthesis, Schedule, SearchParameter, ServiceRequest, Slot, Specimen, SpecimenDefinition, StructureDefinition, StructureMap, Subscription, Substance, SubstanceNucleicAcid, SubstancePolymer, SubstanceProtein, SubstanceReferenceInformation, SubstanceSourceMaterial, SubstanceSpecification, SupplyDelivery, SupplyRequest, Task, TerminologyCapabilities, TestReport, TestScript, ValueSet, VerificationResult, VisionPrescription } from './index';
import { DeviceStatus_list_ValidValues } from '../FhirTsLibValidation/Fhir_ValidValues';



/**
 * A type of a manufactured item that is used in the provision of healthcare without being
 * substantially changed through that activity. The device may be a medical or non-medical device.
 *
 * Generated by Gallaware, Inc. from:
 *    file:/Users/admin/Documents/DevNetbeans/jsonSchemaToJava/target/classes/schema/fhir.schema.json#/definitions/Device
 */
export class Device {
  /**
   * This is a Device resource
   */
     resourceType = "Device";

  /**
   * Any combination of letters, numerals, "-" and ".", with a length limit of 64 characters.  (This
   * might be an integer, an unprefixed OID, UUID or any other identifier pattern that meets these
   * constraints.)  Ids are case-insensitive.
   * Field access restricted because there are specific valid values.
   */
  protected id?: string;

  /**
   * The metadata about a resource. This is content in the resource that is maintained by the
   * infrastructure. Changes to the content might not always be associated with version changes to the
   * resource.
   */
  @Type(() => Meta)
   meta?: Meta;

  /**
   * String of characters used to identify a name or a resource
   * Field access restricted because there are specific valid values.
   */
  protected implicitRules?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _implicitRules?: Element;

  /**
   * A string which has at least one character and no leading or trailing whitespace and where there is
   * no whitespace other than single spaces in the contents
   * Field access restricted because there are specific valid values.
   */
  protected language?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _language?: Element;

  /**
   * A human-readable summary of the resource conveying the essential clinical and business information
   * for the resource.
   */
  @Type(() => Narrative)
   text?: Narrative;

  /**
   * These resources do not have an independent existence apart from the resource that contains them -
   * they cannot be identified independently, and nor can they have their own independent transaction
   * scope.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => ResourceList, {
          discriminator: {
    property: 'resourceType',
    subTypes: [
      	{ value: Account, name: 'Account'},
      	{ value: ActivityDefinition, name: 'ActivityDefinition'},
      	{ value: AdverseEvent, name: 'AdverseEvent'},
      	{ value: AllergyIntolerance, name: 'AllergyIntolerance'},
      	{ value: Appointment, name: 'Appointment'},
      	{ value: AppointmentResponse, name: 'AppointmentResponse'},
      	{ value: AuditEvent, name: 'AuditEvent'},
      	{ value: Basic, name: 'Basic'},
      	{ value: Binary, name: 'Binary'},
      	{ value: BiologicallyDerivedProduct, name: 'BiologicallyDerivedProduct'},
      	{ value: BodyStructure, name: 'BodyStructure'},
      	{ value: Bundle, name: 'Bundle'},
      	{ value: CapabilityStatement, name: 'CapabilityStatement'},
      	{ value: CarePlan, name: 'CarePlan'},
      	{ value: CareTeam, name: 'CareTeam'},
      	{ value: CatalogEntry, name: 'CatalogEntry'},
      	{ value: ChargeItem, name: 'ChargeItem'},
      	{ value: ChargeItemDefinition, name: 'ChargeItemDefinition'},
      	{ value: Claim, name: 'Claim'},
      	{ value: ClaimResponse, name: 'ClaimResponse'},
      	{ value: ClinicalImpression, name: 'ClinicalImpression'},
      	{ value: CodeSystem, name: 'CodeSystem'},
      	{ value: Communication, name: 'Communication'},
      	{ value: CommunicationRequest, name: 'CommunicationRequest'},
      	{ value: CompartmentDefinition, name: 'CompartmentDefinition'},
      	{ value: Composition, name: 'Composition'},
      	{ value: ConceptMap, name: 'ConceptMap'},
      	{ value: Condition, name: 'Condition'},
      	{ value: Consent, name: 'Consent'},
      	{ value: Contract, name: 'Contract'},
      	{ value: Coverage, name: 'Coverage'},
      	{ value: CoverageEligibilityRequest, name: 'CoverageEligibilityRequest'},
      	{ value: CoverageEligibilityResponse, name: 'CoverageEligibilityResponse'},
      	{ value: DetectedIssue, name: 'DetectedIssue'},
      	{ value: Device, name: 'Device'},
      	{ value: DeviceDefinition, name: 'DeviceDefinition'},
      	{ value: DeviceMetric, name: 'DeviceMetric'},
      	{ value: DeviceRequest, name: 'DeviceRequest'},
      	{ value: DeviceUseStatement, name: 'DeviceUseStatement'},
      	{ value: DiagnosticReport, name: 'DiagnosticReport'},
      	{ value: DocumentManifest, name: 'DocumentManifest'},
      	{ value: DocumentReference, name: 'DocumentReference'},
      	{ value: EffectEvidenceSynthesis, name: 'EffectEvidenceSynthesis'},
      	{ value: Encounter, name: 'Encounter'},
      	{ value: Endpoint, name: 'Endpoint'},
      	{ value: EnrollmentRequest, name: 'EnrollmentRequest'},
      	{ value: EnrollmentResponse, name: 'EnrollmentResponse'},
      	{ value: EpisodeOfCare, name: 'EpisodeOfCare'},
      	{ value: EventDefinition, name: 'EventDefinition'},
      	{ value: Evidence, name: 'Evidence'},
      	{ value: EvidenceVariable, name: 'EvidenceVariable'},
      	{ value: ExampleScenario, name: 'ExampleScenario'},
      	{ value: ExplanationOfBenefit, name: 'ExplanationOfBenefit'},
      	{ value: FamilyMemberHistory, name: 'FamilyMemberHistory'},
      	{ value: Flag, name: 'Flag'},
      	{ value: Goal, name: 'Goal'},
      	{ value: GraphDefinition, name: 'GraphDefinition'},
      	{ value: Group, name: 'Group'},
      	{ value: GuidanceResponse, name: 'GuidanceResponse'},
      	{ value: HealthcareService, name: 'HealthcareService'},
      	{ value: ImagingStudy, name: 'ImagingStudy'},
      	{ value: Immunization, name: 'Immunization'},
      	{ value: ImmunizationEvaluation, name: 'ImmunizationEvaluation'},
      	{ value: ImmunizationRecommendation, name: 'ImmunizationRecommendation'},
      	{ value: ImplementationGuide, name: 'ImplementationGuide'},
      	{ value: InsurancePlan, name: 'InsurancePlan'},
      	{ value: Invoice, name: 'Invoice'},
      	{ value: Library, name: 'Library'},
      	{ value: Linkage, name: 'Linkage'},
      	{ value: List, name: 'List'},
      	{ value: Location, name: 'Location'},
      	{ value: Measure, name: 'Measure'},
      	{ value: MeasureReport, name: 'MeasureReport'},
      	{ value: Media, name: 'Media'},
      	{ value: Medication, name: 'Medication'},
      	{ value: MedicationAdministration, name: 'MedicationAdministration'},
      	{ value: MedicationDispense, name: 'MedicationDispense'},
      	{ value: MedicationKnowledge, name: 'MedicationKnowledge'},
      	{ value: MedicationRequest, name: 'MedicationRequest'},
      	{ value: MedicationStatement, name: 'MedicationStatement'},
      	{ value: MedicinalProduct, name: 'MedicinalProduct'},
      	{ value: MedicinalProductAuthorization, name: 'MedicinalProductAuthorization'},
      	{ value: MedicinalProductContraindication, name: 'MedicinalProductContraindication'},
      	{ value: MedicinalProductIndication, name: 'MedicinalProductIndication'},
      	{ value: MedicinalProductIngredient, name: 'MedicinalProductIngredient'},
      	{ value: MedicinalProductInteraction, name: 'MedicinalProductInteraction'},
      	{ value: MedicinalProductManufactured, name: 'MedicinalProductManufactured'},
      	{ value: MedicinalProductPackaged, name: 'MedicinalProductPackaged'},
      	{ value: MedicinalProductPharmaceutical, name: 'MedicinalProductPharmaceutical'},
      	{ value: MedicinalProductUndesirableEffect, name: 'MedicinalProductUndesirableEffect'},
      	{ value: MessageDefinition, name: 'MessageDefinition'},
      	{ value: MessageHeader, name: 'MessageHeader'},
      	{ value: MolecularSequence, name: 'MolecularSequence'},
      	{ value: NamingSystem, name: 'NamingSystem'},
      	{ value: NutritionOrder, name: 'NutritionOrder'},
      	{ value: Observation, name: 'Observation'},
      	{ value: ObservationDefinition, name: 'ObservationDefinition'},
      	{ value: OperationDefinition, name: 'OperationDefinition'},
      	{ value: OperationOutcome, name: 'OperationOutcome'},
      	{ value: Organization, name: 'Organization'},
      	{ value: OrganizationAffiliation, name: 'OrganizationAffiliation'},
      	{ value: Parameters, name: 'Parameters'},
      	{ value: Patient, name: 'Patient'},
      	{ value: PaymentNotice, name: 'PaymentNotice'},
      	{ value: PaymentReconciliation, name: 'PaymentReconciliation'},
      	{ value: Person, name: 'Person'},
      	{ value: PlanDefinition, name: 'PlanDefinition'},
      	{ value: Practitioner, name: 'Practitioner'},
      	{ value: PractitionerRole, name: 'PractitionerRole'},
      	{ value: Procedure, name: 'Procedure'},
      	{ value: Provenance, name: 'Provenance'},
      	{ value: Questionnaire, name: 'Questionnaire'},
      	{ value: QuestionnaireResponse, name: 'QuestionnaireResponse'},
      	{ value: RelatedPerson, name: 'RelatedPerson'},
      	{ value: RequestGroup, name: 'RequestGroup'},
      	{ value: ResearchDefinition, name: 'ResearchDefinition'},
      	{ value: ResearchElementDefinition, name: 'ResearchElementDefinition'},
      	{ value: ResearchStudy, name: 'ResearchStudy'},
      	{ value: ResearchSubject, name: 'ResearchSubject'},
      	{ value: RiskAssessment, name: 'RiskAssessment'},
      	{ value: RiskEvidenceSynthesis, name: 'RiskEvidenceSynthesis'},
      	{ value: Schedule, name: 'Schedule'},
      	{ value: SearchParameter, name: 'SearchParameter'},
      	{ value: ServiceRequest, name: 'ServiceRequest'},
      	{ value: Slot, name: 'Slot'},
      	{ value: Specimen, name: 'Specimen'},
      	{ value: SpecimenDefinition, name: 'SpecimenDefinition'},
      	{ value: StructureDefinition, name: 'StructureDefinition'},
      	{ value: StructureMap, name: 'StructureMap'},
      	{ value: Subscription, name: 'Subscription'},
      	{ value: Substance, name: 'Substance'},
      	{ value: SubstanceNucleicAcid, name: 'SubstanceNucleicAcid'},
      	{ value: SubstancePolymer, name: 'SubstancePolymer'},
      	{ value: SubstanceProtein, name: 'SubstanceProtein'},
      	{ value: SubstanceReferenceInformation, name: 'SubstanceReferenceInformation'},
      	{ value: SubstanceSourceMaterial, name: 'SubstanceSourceMaterial'},
      	{ value: SubstanceSpecification, name: 'SubstanceSpecification'},
      	{ value: SupplyDelivery, name: 'SupplyDelivery'},
      	{ value: SupplyRequest, name: 'SupplyRequest'},
      	{ value: Task, name: 'Task'},
      	{ value: TerminologyCapabilities, name: 'TerminologyCapabilities'},
      	{ value: TestReport, name: 'TestReport'},
      	{ value: TestScript, name: 'TestScript'},
      	{ value: ValueSet, name: 'ValueSet'},
      	{ value: VerificationResult, name: 'VerificationResult'},
      	{ value: VisionPrescription, name: 'VisionPrescription'}
      ],
    }
  })
  protected contained?: ResourceList[];

  /**
   * May be used to represent additional information that is not part of the basic definition of the
   * resource. To make the use of extensions safe and manageable, there is a strict set of governance
   * applied to the definition and use of extensions. Though any implementer can define an extension,
   * there is a set of requirements that SHALL be met as part of the definition of the extension.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Extension)
  protected extension?: Extension[];

  /**
   * May be used to represent additional information that is not part of the basic definition of the
   * resource and that modifies the understanding of the element that contains it and/or the
   * understanding of the containing element's descendants. Usually modifier elements provide negation
   * or qualification. To make the use of extensions safe and manageable, there is a strict set of
   * governance applied to the definition and use of extensions. Though any implementer is allowed to
   * define an extension, there is a set of requirements that SHALL be met as part of the definition of
   * the extension. Applications processing a resource are required to check for modifier extensions.
   * 
   * Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource
   * (including cannot change the meaning of modifierExtension itself).
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Extension)
  protected modifierExtension?: Extension[];

  /**
   * Unique instance identifiers assigned to a device by manufacturers other organizations or owners.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Identifier)
  protected identifier?: Identifier[];

  /**
   * A reference from one resource to another.
   */
  @Type(() => Reference)
   definition?: Reference;

  /**
   * Unique device identifier (UDI) assigned to device label or package.  Note that the Device may
   * include multiple udiCarriers as it either may include just the udiCarrier for the jurisdiction it
   * is sold, or for multiple jurisdictions it could have been sold.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => DeviceUdiCarrier)
  protected udiCarrier?: DeviceUdiCarrier[];

  /**
   * Status of the Device availability.
   * Field access restricted because there are specific valid values.
   */
  protected status?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _status?: Element;

  /**
   * Reason for the dtatus of the Device availability.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => CodeableConcept)
  protected statusReason?: CodeableConcept[];

  /**
   * A sequence of Unicode characters
   * Field access restricted because there are specific valid values.
   */
  protected distinctIdentifier?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _distinctIdentifier?: Element;

  /**
   * A sequence of Unicode characters
   * Field access restricted because there are specific valid values.
   */
  protected manufacturer?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _manufacturer?: Element;

  /**
   * A date, date-time or partial date (e.g. just year or year + month).  If hours and minutes are
   * specified, a time zone SHALL be populated. The format is a union of the schema types gYear,
   * gYearMonth, date and dateTime. Seconds must be provided due to schema type constraints but may be
   * zero-filled and may be ignored.                 Dates SHALL be valid dates.
   * Field access restricted because there are specific valid values.
   */
  protected manufactureDate?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _manufactureDate?: Element;

  /**
   * A date, date-time or partial date (e.g. just year or year + month).  If hours and minutes are
   * specified, a time zone SHALL be populated. The format is a union of the schema types gYear,
   * gYearMonth, date and dateTime. Seconds must be provided due to schema type constraints but may be
   * zero-filled and may be ignored.                 Dates SHALL be valid dates.
   * Field access restricted because there are specific valid values.
   */
  protected expirationDate?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _expirationDate?: Element;

  /**
   * A sequence of Unicode characters
   * Field access restricted because there are specific valid values.
   */
  protected lotNumber?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _lotNumber?: Element;

  /**
   * A sequence of Unicode characters
   * Field access restricted because there are specific valid values.
   */
  protected serialNumber?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _serialNumber?: Element;

  /**
   * This represents the manufacturer's name of the device as provided by the device, from a UDI label,
   * or by a person describing the Device.  This typically would be used when a person provides the
   * name(s) or when the device represents one of the names available from DeviceDefinition.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => DeviceDeviceName)
  protected deviceName?: DeviceDeviceName[];

  /**
   * A sequence of Unicode characters
   * Field access restricted because there are specific valid values.
   */
  protected modelNumber?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _modelNumber?: Element;

  /**
   * A sequence of Unicode characters
   * Field access restricted because there are specific valid values.
   */
  protected partNumber?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _partNumber?: Element;

  /**
   * A concept that may be defined by a formal reference to a terminology or ontology or may be provided
   * by text.
   */
  @Type(() => CodeableConcept)
   type?: CodeableConcept;

  /**
   * The capabilities supported on a  device, the standards to which the device conforms for a
   * particular purpose, and used for the communication.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => DeviceSpecialization)
  protected specialization?: DeviceSpecialization[];

  /**
   * The actual design of the device or software version running on the device.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => DeviceVersion)
  protected version?: DeviceVersion[];

  /**
   * The actual configuration settings of a device as it actually operates, e.g., regulation status,
   * time properties.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => DeviceProperty)
  protected property?: DeviceProperty[];

  /**
   * A reference from one resource to another.
   */
  @Type(() => Reference)
   patient?: Reference;

  /**
   * A reference from one resource to another.
   */
  @Type(() => Reference)
   owner?: Reference;

  /**
   * Contact details for an organization or a particular human that is responsible for the device.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => ContactPoint)
  protected contact?: ContactPoint[];

  /**
   * A reference from one resource to another.
   */
  @Type(() => Reference)
   location?: Reference;

  /**
   * String of characters used to identify a name or a resource
   * Field access restricted because there are specific valid values.
   */
  protected url?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _url?: Element;

  /**
   * Descriptive information, usage information or implantation information that is not captured in an
   * existing element.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Annotation)
  protected note?: Annotation[];

  /**
   * Provides additional safety characteristics about a medical device.  For example devices containing
   * latex.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => CodeableConcept)
  protected safety?: CodeableConcept[];

  /**
   * A reference from one resource to another.
   */
  @Type(() => Reference)
   parent?: Reference;


  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setId(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.id) !== 'undefined') {
         delete this.id;
      }
      return;
    }
    
    if (REGEX_ID_000.test(newValue)) {
      this.id = newValue
    } else {
      throw new Error("Invalid value pattern for id of " + newValue);
    }
  }
  
  public getIdPattern(): string {
    return REGEX_ID_000.source;
  }
  
  /**
  * Gets the current value of field id.
  * @returns the value  or undefined
  */
  public getId(): string | undefined {
      return this.id;
  }

  /**
  * Gets the current value of field id if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getIdOrElse(defaultValue: string): string {
      if (this.id == undefined || this.id == null ) { return defaultValue; }
      return this.id;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setImplicitRules(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.implicitRules) !== 'undefined') {
         delete this.implicitRules;
      }
      return;
    }
    
    if (REGEX_IMPLICITRULES.test(newValue)) {
      this.implicitRules = newValue
    } else {
      throw new Error("Invalid value pattern for implicitRules of " + newValue);
    }
  }
  
  public getImplicitRulesPattern(): string {
    return REGEX_IMPLICITRULES.source;
  }
  
  /**
  * Gets the current value of field implicitRules.
  * @returns the value  or undefined
  */
  public getImplicitRules(): string | undefined {
      return this.implicitRules;
  }

  /**
  * Gets the current value of field implicitRules if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getImplicitRulesOrElse(defaultValue: string): string {
      if (this.implicitRules == undefined || this.implicitRules == null ) { return defaultValue; }
      return this.implicitRules;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setLanguage(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.language) !== 'undefined') {
         delete this.language;
      }
      return;
    }
    
    if (REGEX_LANGUAGE.test(newValue)) {
      this.language = newValue
    } else {
      throw new Error("Invalid value pattern for language of " + newValue);
    }
  }
  
  public getLanguagePattern(): string {
    return REGEX_LANGUAGE.source;
  }
  
  /**
  * Gets the current value of field language.
  * @returns the value  or undefined
  */
  public getLanguage(): string | undefined {
      return this.language;
  }

  /**
  * Gets the current value of field language if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getLanguageOrElse(defaultValue: string): string {
      if (this.language == undefined || this.language == null ) { return defaultValue; }
      return this.language;
  }

  public addContained(newValue: ResourceList) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.contained) !== 'undefined') {
         delete this.contained;
      }
      return;
    }
    
    if (typeof(this.contained) === 'undefined') {
      this.contained =  [];
    }
    this.contained.push(newValue);
  }
  /**
  * Removes all elements from the array contained, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteContainedAll(): ResourceList[] {
    if (typeof(this.contained) !== 'undefined') {
       const oldArray = this.contained;
       delete this.contained;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array contained, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteContainedBySplice(start: number, deleteCount?: number): ResourceList[] {
    if (typeof(this.contained) !== 'undefined') {
       return this.contained.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field contained.
  * @returns the value  or undefined
  */
  public getContained(): ResourceList[] | undefined {
      return this.contained;
  }

  /**
  * Gets the current value of field contained if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getContainedOrElse(defaultValue: ResourceList[]): ResourceList[] {
      if (this.contained == undefined || this.contained == null ) { return defaultValue; }
      return this.contained;
  }

  public addExtension(newValue: Extension) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.extension) !== 'undefined') {
         delete this.extension;
      }
      return;
    }
    
    if (typeof(this.extension) === 'undefined') {
      this.extension =  [];
    }
    this.extension.push(newValue);
  }
  /**
  * Removes all elements from the array extension, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteExtensionAll(): Extension[] {
    if (typeof(this.extension) !== 'undefined') {
       const oldArray = this.extension;
       delete this.extension;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array extension, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteExtensionBySplice(start: number, deleteCount?: number): Extension[] {
    if (typeof(this.extension) !== 'undefined') {
       return this.extension.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field extension.
  * @returns the value  or undefined
  */
  public getExtension(): Extension[] | undefined {
      return this.extension;
  }

  /**
  * Gets the current value of field extension if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getExtensionOrElse(defaultValue: Extension[]): Extension[] {
      if (this.extension == undefined || this.extension == null ) { return defaultValue; }
      return this.extension;
  }

  public addModifierExtension(newValue: Extension) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.modifierExtension) !== 'undefined') {
         delete this.modifierExtension;
      }
      return;
    }
    
    if (typeof(this.modifierExtension) === 'undefined') {
      this.modifierExtension =  [];
    }
    this.modifierExtension.push(newValue);
  }
  /**
  * Removes all elements from the array modifierExtension, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteModifierExtensionAll(): Extension[] {
    if (typeof(this.modifierExtension) !== 'undefined') {
       const oldArray = this.modifierExtension;
       delete this.modifierExtension;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array modifierExtension, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteModifierExtensionBySplice(start: number, deleteCount?: number): Extension[] {
    if (typeof(this.modifierExtension) !== 'undefined') {
       return this.modifierExtension.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field modifierExtension.
  * @returns the value  or undefined
  */
  public getModifierExtension(): Extension[] | undefined {
      return this.modifierExtension;
  }

  /**
  * Gets the current value of field modifierExtension if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getModifierExtensionOrElse(defaultValue: Extension[]): Extension[] {
      if (this.modifierExtension == undefined || this.modifierExtension == null ) { return defaultValue; }
      return this.modifierExtension;
  }

  public addIdentifier(newValue: Identifier) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.identifier) !== 'undefined') {
         delete this.identifier;
      }
      return;
    }
    
    if (typeof(this.identifier) === 'undefined') {
      this.identifier =  [];
    }
    this.identifier.push(newValue);
  }
  /**
  * Removes all elements from the array identifier, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteIdentifierAll(): Identifier[] {
    if (typeof(this.identifier) !== 'undefined') {
       const oldArray = this.identifier;
       delete this.identifier;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array identifier, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteIdentifierBySplice(start: number, deleteCount?: number): Identifier[] {
    if (typeof(this.identifier) !== 'undefined') {
       return this.identifier.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field identifier.
  * @returns the value  or undefined
  */
  public getIdentifier(): Identifier[] | undefined {
      return this.identifier;
  }

  /**
  * Gets the current value of field identifier if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getIdentifierOrElse(defaultValue: Identifier[]): Identifier[] {
      if (this.identifier == undefined || this.identifier == null ) { return defaultValue; }
      return this.identifier;
  }

  public addUdiCarrier(newValue: DeviceUdiCarrier) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.udiCarrier) !== 'undefined') {
         delete this.udiCarrier;
      }
      return;
    }
    
    if (typeof(this.udiCarrier) === 'undefined') {
      this.udiCarrier =  [];
    }
    this.udiCarrier.push(newValue);
  }
  /**
  * Removes all elements from the array udiCarrier, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteUdiCarrierAll(): DeviceUdiCarrier[] {
    if (typeof(this.udiCarrier) !== 'undefined') {
       const oldArray = this.udiCarrier;
       delete this.udiCarrier;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array udiCarrier, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteUdiCarrierBySplice(start: number, deleteCount?: number): DeviceUdiCarrier[] {
    if (typeof(this.udiCarrier) !== 'undefined') {
       return this.udiCarrier.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field udiCarrier.
  * @returns the value  or undefined
  */
  public getUdiCarrier(): DeviceUdiCarrier[] | undefined {
      return this.udiCarrier;
  }

  /**
  * Gets the current value of field udiCarrier if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getUdiCarrierOrElse(defaultValue: DeviceUdiCarrier[]): DeviceUdiCarrier[] {
      if (this.udiCarrier == undefined || this.udiCarrier == null ) { return defaultValue; }
      return this.udiCarrier;
  }

  /*
  * This sets the data ensuring that the value is valid.  If not valid, it throws an error
  * that should be caught.
  */
  public setStatus(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.status) !== 'undefined') {
         delete this.status;
      }
      return;
    }
    
    const idx = getValidValueIdx(DeviceStatus_list_ValidValues, newValue);
    if (idx >= 0) {
      this.status = DeviceStatus_list_ValidValues[idx];
    } else {
      throw new Error("Unknown status of " + newValue);
    }
  }
  
  public getDeviceStatusValidValues(): string[] {
    return DeviceStatus_list_ValidValues;
  }
  
  /**
  * Gets the current value of field status.
  * @returns the value  or undefined
  */
  public getStatus(): string | undefined {
      return this.status;
  }

  /**
  * Gets the current value of field status if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getStatusOrElse(defaultValue: string): string {
      if (this.status == undefined || this.status == null ) { return defaultValue; }
      return this.status;
  }

  public addStatusReason(newValue: CodeableConcept) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.statusReason) !== 'undefined') {
         delete this.statusReason;
      }
      return;
    }
    
    if (typeof(this.statusReason) === 'undefined') {
      this.statusReason =  [];
    }
    this.statusReason.push(newValue);
  }
  /**
  * Removes all elements from the array statusReason, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteStatusReasonAll(): CodeableConcept[] {
    if (typeof(this.statusReason) !== 'undefined') {
       const oldArray = this.statusReason;
       delete this.statusReason;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array statusReason, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteStatusReasonBySplice(start: number, deleteCount?: number): CodeableConcept[] {
    if (typeof(this.statusReason) !== 'undefined') {
       return this.statusReason.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field statusReason.
  * @returns the value  or undefined
  */
  public getStatusReason(): CodeableConcept[] | undefined {
      return this.statusReason;
  }

  /**
  * Gets the current value of field statusReason if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getStatusReasonOrElse(defaultValue: CodeableConcept[]): CodeableConcept[] {
      if (this.statusReason == undefined || this.statusReason == null ) { return defaultValue; }
      return this.statusReason;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setDistinctIdentifier(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.distinctIdentifier) !== 'undefined') {
         delete this.distinctIdentifier;
      }
      return;
    }
    
    if (REGEX_DISTINCTIDENTIFIER.test(newValue)) {
      this.distinctIdentifier = newValue
    } else {
      throw new Error("Invalid value pattern for distinctIdentifier of " + newValue);
    }
  }
  
  public getDistinctIdentifierPattern(): string {
    return REGEX_DISTINCTIDENTIFIER.source;
  }
  
  /**
  * Gets the current value of field distinctIdentifier.
  * @returns the value  or undefined
  */
  public getDistinctIdentifier(): string | undefined {
      return this.distinctIdentifier;
  }

  /**
  * Gets the current value of field distinctIdentifier if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getDistinctIdentifierOrElse(defaultValue: string): string {
      if (this.distinctIdentifier == undefined || this.distinctIdentifier == null ) { return defaultValue; }
      return this.distinctIdentifier;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setManufacturer(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.manufacturer) !== 'undefined') {
         delete this.manufacturer;
      }
      return;
    }
    
    if (REGEX_MANUFACTURER.test(newValue)) {
      this.manufacturer = newValue
    } else {
      throw new Error("Invalid value pattern for manufacturer of " + newValue);
    }
  }
  
  public getManufacturerPattern(): string {
    return REGEX_MANUFACTURER.source;
  }
  
  /**
  * Gets the current value of field manufacturer.
  * @returns the value  or undefined
  */
  public getManufacturer(): string | undefined {
      return this.manufacturer;
  }

  /**
  * Gets the current value of field manufacturer if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getManufacturerOrElse(defaultValue: string): string {
      if (this.manufacturer == undefined || this.manufacturer == null ) { return defaultValue; }
      return this.manufacturer;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setManufactureDate(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.manufactureDate) !== 'undefined') {
         delete this.manufactureDate;
      }
      return;
    }
    
    if (REGEX_MANUFACTUREDATE.test(newValue)) {
      this.manufactureDate = newValue
    } else {
      throw new Error("Invalid value pattern for manufactureDate of " + newValue);
    }
  }
  
  public getManufactureDatePattern(): string {
    return REGEX_MANUFACTUREDATE.source;
  }
  
  /**
  * Gets the current value of field manufactureDate.
  * @returns the value  or undefined
  */
  public getManufactureDate(): string | undefined {
      return this.manufactureDate;
  }

  /**
  * Gets the current value of field manufactureDate if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getManufactureDateOrElse(defaultValue: string): string {
      if (this.manufactureDate == undefined || this.manufactureDate == null ) { return defaultValue; }
      return this.manufactureDate;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setExpirationDate(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.expirationDate) !== 'undefined') {
         delete this.expirationDate;
      }
      return;
    }
    
    if (REGEX_EXPIRATIONDATE.test(newValue)) {
      this.expirationDate = newValue
    } else {
      throw new Error("Invalid value pattern for expirationDate of " + newValue);
    }
  }
  
  public getExpirationDatePattern(): string {
    return REGEX_EXPIRATIONDATE.source;
  }
  
  /**
  * Gets the current value of field expirationDate.
  * @returns the value  or undefined
  */
  public getExpirationDate(): string | undefined {
      return this.expirationDate;
  }

  /**
  * Gets the current value of field expirationDate if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getExpirationDateOrElse(defaultValue: string): string {
      if (this.expirationDate == undefined || this.expirationDate == null ) { return defaultValue; }
      return this.expirationDate;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setLotNumber(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.lotNumber) !== 'undefined') {
         delete this.lotNumber;
      }
      return;
    }
    
    if (REGEX_LOTNUMBER.test(newValue)) {
      this.lotNumber = newValue
    } else {
      throw new Error("Invalid value pattern for lotNumber of " + newValue);
    }
  }
  
  public getLotNumberPattern(): string {
    return REGEX_LOTNUMBER.source;
  }
  
  /**
  * Gets the current value of field lotNumber.
  * @returns the value  or undefined
  */
  public getLotNumber(): string | undefined {
      return this.lotNumber;
  }

  /**
  * Gets the current value of field lotNumber if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getLotNumberOrElse(defaultValue: string): string {
      if (this.lotNumber == undefined || this.lotNumber == null ) { return defaultValue; }
      return this.lotNumber;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setSerialNumber(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.serialNumber) !== 'undefined') {
         delete this.serialNumber;
      }
      return;
    }
    
    if (REGEX_SERIALNUMBER.test(newValue)) {
      this.serialNumber = newValue
    } else {
      throw new Error("Invalid value pattern for serialNumber of " + newValue);
    }
  }
  
  public getSerialNumberPattern(): string {
    return REGEX_SERIALNUMBER.source;
  }
  
  /**
  * Gets the current value of field serialNumber.
  * @returns the value  or undefined
  */
  public getSerialNumber(): string | undefined {
      return this.serialNumber;
  }

  /**
  * Gets the current value of field serialNumber if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getSerialNumberOrElse(defaultValue: string): string {
      if (this.serialNumber == undefined || this.serialNumber == null ) { return defaultValue; }
      return this.serialNumber;
  }

  public addDeviceName(newValue: DeviceDeviceName) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.deviceName) !== 'undefined') {
         delete this.deviceName;
      }
      return;
    }
    
    if (typeof(this.deviceName) === 'undefined') {
      this.deviceName =  [];
    }
    this.deviceName.push(newValue);
  }
  /**
  * Removes all elements from the array deviceName, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteDeviceNameAll(): DeviceDeviceName[] {
    if (typeof(this.deviceName) !== 'undefined') {
       const oldArray = this.deviceName;
       delete this.deviceName;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array deviceName, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteDeviceNameBySplice(start: number, deleteCount?: number): DeviceDeviceName[] {
    if (typeof(this.deviceName) !== 'undefined') {
       return this.deviceName.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field deviceName.
  * @returns the value  or undefined
  */
  public getDeviceName(): DeviceDeviceName[] | undefined {
      return this.deviceName;
  }

  /**
  * Gets the current value of field deviceName if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getDeviceNameOrElse(defaultValue: DeviceDeviceName[]): DeviceDeviceName[] {
      if (this.deviceName == undefined || this.deviceName == null ) { return defaultValue; }
      return this.deviceName;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setModelNumber(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.modelNumber) !== 'undefined') {
         delete this.modelNumber;
      }
      return;
    }
    
    if (REGEX_MODELNUMBER.test(newValue)) {
      this.modelNumber = newValue
    } else {
      throw new Error("Invalid value pattern for modelNumber of " + newValue);
    }
  }
  
  public getModelNumberPattern(): string {
    return REGEX_MODELNUMBER.source;
  }
  
  /**
  * Gets the current value of field modelNumber.
  * @returns the value  or undefined
  */
  public getModelNumber(): string | undefined {
      return this.modelNumber;
  }

  /**
  * Gets the current value of field modelNumber if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getModelNumberOrElse(defaultValue: string): string {
      if (this.modelNumber == undefined || this.modelNumber == null ) { return defaultValue; }
      return this.modelNumber;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setPartNumber(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.partNumber) !== 'undefined') {
         delete this.partNumber;
      }
      return;
    }
    
    if (REGEX_PARTNUMBER.test(newValue)) {
      this.partNumber = newValue
    } else {
      throw new Error("Invalid value pattern for partNumber of " + newValue);
    }
  }
  
  public getPartNumberPattern(): string {
    return REGEX_PARTNUMBER.source;
  }
  
  /**
  * Gets the current value of field partNumber.
  * @returns the value  or undefined
  */
  public getPartNumber(): string | undefined {
      return this.partNumber;
  }

  /**
  * Gets the current value of field partNumber if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getPartNumberOrElse(defaultValue: string): string {
      if (this.partNumber == undefined || this.partNumber == null ) { return defaultValue; }
      return this.partNumber;
  }

  public addSpecialization(newValue: DeviceSpecialization) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.specialization) !== 'undefined') {
         delete this.specialization;
      }
      return;
    }
    
    if (typeof(this.specialization) === 'undefined') {
      this.specialization =  [];
    }
    this.specialization.push(newValue);
  }
  /**
  * Removes all elements from the array specialization, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteSpecializationAll(): DeviceSpecialization[] {
    if (typeof(this.specialization) !== 'undefined') {
       const oldArray = this.specialization;
       delete this.specialization;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array specialization, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteSpecializationBySplice(start: number, deleteCount?: number): DeviceSpecialization[] {
    if (typeof(this.specialization) !== 'undefined') {
       return this.specialization.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field specialization.
  * @returns the value  or undefined
  */
  public getSpecialization(): DeviceSpecialization[] | undefined {
      return this.specialization;
  }

  /**
  * Gets the current value of field specialization if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getSpecializationOrElse(defaultValue: DeviceSpecialization[]): DeviceSpecialization[] {
      if (this.specialization == undefined || this.specialization == null ) { return defaultValue; }
      return this.specialization;
  }

  public addVersion(newValue: DeviceVersion) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.version) !== 'undefined') {
         delete this.version;
      }
      return;
    }
    
    if (typeof(this.version) === 'undefined') {
      this.version =  [];
    }
    this.version.push(newValue);
  }
  /**
  * Removes all elements from the array version, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteVersionAll(): DeviceVersion[] {
    if (typeof(this.version) !== 'undefined') {
       const oldArray = this.version;
       delete this.version;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array version, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteVersionBySplice(start: number, deleteCount?: number): DeviceVersion[] {
    if (typeof(this.version) !== 'undefined') {
       return this.version.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field version.
  * @returns the value  or undefined
  */
  public getVersion(): DeviceVersion[] | undefined {
      return this.version;
  }

  /**
  * Gets the current value of field version if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getVersionOrElse(defaultValue: DeviceVersion[]): DeviceVersion[] {
      if (this.version == undefined || this.version == null ) { return defaultValue; }
      return this.version;
  }

  public addProperty(newValue: DeviceProperty) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.property) !== 'undefined') {
         delete this.property;
      }
      return;
    }
    
    if (typeof(this.property) === 'undefined') {
      this.property =  [];
    }
    this.property.push(newValue);
  }
  /**
  * Removes all elements from the array property, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deletePropertyAll(): DeviceProperty[] {
    if (typeof(this.property) !== 'undefined') {
       const oldArray = this.property;
       delete this.property;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array property, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deletePropertyBySplice(start: number, deleteCount?: number): DeviceProperty[] {
    if (typeof(this.property) !== 'undefined') {
       return this.property.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field property.
  * @returns the value  or undefined
  */
  public getProperty(): DeviceProperty[] | undefined {
      return this.property;
  }

  /**
  * Gets the current value of field property if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getPropertyOrElse(defaultValue: DeviceProperty[]): DeviceProperty[] {
      if (this.property == undefined || this.property == null ) { return defaultValue; }
      return this.property;
  }

  public addContact(newValue: ContactPoint) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.contact) !== 'undefined') {
         delete this.contact;
      }
      return;
    }
    
    if (typeof(this.contact) === 'undefined') {
      this.contact =  [];
    }
    this.contact.push(newValue);
  }
  /**
  * Removes all elements from the array contact, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteContactAll(): ContactPoint[] {
    if (typeof(this.contact) !== 'undefined') {
       const oldArray = this.contact;
       delete this.contact;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array contact, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteContactBySplice(start: number, deleteCount?: number): ContactPoint[] {
    if (typeof(this.contact) !== 'undefined') {
       return this.contact.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field contact.
  * @returns the value  or undefined
  */
  public getContact(): ContactPoint[] | undefined {
      return this.contact;
  }

  /**
  * Gets the current value of field contact if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getContactOrElse(defaultValue: ContactPoint[]): ContactPoint[] {
      if (this.contact == undefined || this.contact == null ) { return defaultValue; }
      return this.contact;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setUrl(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.url) !== 'undefined') {
         delete this.url;
      }
      return;
    }
    
    if (REGEX_URL.test(newValue)) {
      this.url = newValue
    } else {
      throw new Error("Invalid value pattern for url of " + newValue);
    }
  }
  
  public getUrlPattern(): string {
    return REGEX_URL.source;
  }
  
  /**
  * Gets the current value of field url.
  * @returns the value  or undefined
  */
  public getUrl(): string | undefined {
      return this.url;
  }

  /**
  * Gets the current value of field url if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getUrlOrElse(defaultValue: string): string {
      if (this.url == undefined || this.url == null ) { return defaultValue; }
      return this.url;
  }

  public addNote(newValue: Annotation) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.note) !== 'undefined') {
         delete this.note;
      }
      return;
    }
    
    if (typeof(this.note) === 'undefined') {
      this.note =  [];
    }
    this.note.push(newValue);
  }
  /**
  * Removes all elements from the array note, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteNoteAll(): Annotation[] {
    if (typeof(this.note) !== 'undefined') {
       const oldArray = this.note;
       delete this.note;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array note, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteNoteBySplice(start: number, deleteCount?: number): Annotation[] {
    if (typeof(this.note) !== 'undefined') {
       return this.note.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field note.
  * @returns the value  or undefined
  */
  public getNote(): Annotation[] | undefined {
      return this.note;
  }

  /**
  * Gets the current value of field note if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getNoteOrElse(defaultValue: Annotation[]): Annotation[] {
      if (this.note == undefined || this.note == null ) { return defaultValue; }
      return this.note;
  }

  public addSafety(newValue: CodeableConcept) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.safety) !== 'undefined') {
         delete this.safety;
      }
      return;
    }
    
    if (typeof(this.safety) === 'undefined') {
      this.safety =  [];
    }
    this.safety.push(newValue);
  }
  /**
  * Removes all elements from the array safety, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteSafetyAll(): CodeableConcept[] {
    if (typeof(this.safety) !== 'undefined') {
       const oldArray = this.safety;
       delete this.safety;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array safety, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteSafetyBySplice(start: number, deleteCount?: number): CodeableConcept[] {
    if (typeof(this.safety) !== 'undefined') {
       return this.safety.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field safety.
  * @returns the value  or undefined
  */
  public getSafety(): CodeableConcept[] | undefined {
      return this.safety;
  }

  /**
  * Gets the current value of field safety if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getSafetyOrElse(defaultValue: CodeableConcept[]): CodeableConcept[] {
      if (this.safety == undefined || this.safety == null ) { return defaultValue; }
      return this.safety;
  }


}


