import { Type } from 'class-transformer';
import { REGEX_ID_000, REGEX_IMPLICITRULES, REGEX_LANGUAGE, REGEX_STATUS_000, REGEX_INTENT, REGEX_PRIORITY, REGEX_AUTHOREDON } from '../FhirTsLibValidation/FhirRegex';
import { Annotation, CodeableConcept, Dosage, Element, Extension, Identifier, MedicationRequestDispenseRequest, MedicationRequestSubstitution, Meta, Narrative, Reference, ResourceList, Account, ActivityDefinition, AdverseEvent, AllergyIntolerance, Appointment, AppointmentResponse, AuditEvent, Basic, Binary, BiologicallyDerivedProduct, BodyStructure, Bundle, CapabilityStatement, CarePlan, CareTeam, CatalogEntry, ChargeItem, ChargeItemDefinition, Claim, ClaimResponse, ClinicalImpression, CodeSystem, Communication, CommunicationRequest, CompartmentDefinition, Composition, ConceptMap, Condition, Consent, Contract, Coverage, CoverageEligibilityRequest, CoverageEligibilityResponse, DetectedIssue, Device, DeviceDefinition, DeviceMetric, DeviceRequest, DeviceUseStatement, DiagnosticReport, DocumentManifest, DocumentReference, EffectEvidenceSynthesis, Encounter, Endpoint, EnrollmentRequest, EnrollmentResponse, EpisodeOfCare, EventDefinition, Evidence, EvidenceVariable, ExampleScenario, ExplanationOfBenefit, FamilyMemberHistory, Flag, Goal, GraphDefinition, Group, GuidanceResponse, HealthcareService, ImagingStudy, Immunization, ImmunizationEvaluation, ImmunizationRecommendation, ImplementationGuide, InsurancePlan, Invoice, Library, Linkage, List, Location, Measure, MeasureReport, Media, Medication, MedicationAdministration, MedicationDispense, MedicationKnowledge, MedicationStatement, MedicinalProduct, MedicinalProductAuthorization, MedicinalProductContraindication, MedicinalProductIndication, MedicinalProductIngredient, MedicinalProductInteraction, MedicinalProductManufactured, MedicinalProductPackaged, MedicinalProductPharmaceutical, MedicinalProductUndesirableEffect, MessageDefinition, MessageHeader, MolecularSequence, NamingSystem, NutritionOrder, Observation, ObservationDefinition, OperationDefinition, OperationOutcome, Organization, OrganizationAffiliation, Parameters, Patient, PaymentNotice, PaymentReconciliation, Person, PlanDefinition, Practitioner, PractitionerRole, Procedure, Provenance, Questionnaire, QuestionnaireResponse, RelatedPerson, RequestGroup, ResearchDefinition, ResearchElementDefinition, ResearchStudy, ResearchSubject, RiskAssessment, RiskEvidenceSynthesis, Schedule, SearchParameter, ServiceRequest, Slot, Specimen, SpecimenDefinition, StructureDefinition, StructureMap, Subscription, Substance, SubstanceNucleicAcid, SubstancePolymer, SubstanceProtein, SubstanceReferenceInformation, SubstanceSourceMaterial, SubstanceSpecification, SupplyDelivery, SupplyRequest, Task, TerminologyCapabilities, TestReport, TestScript, ValueSet, VerificationResult, VisionPrescription } from './index';



/**
 * An order or request for both supply of the medication and the instructions for administration of
 * the medication to a patient. The resource is called "MedicationRequest" rather than
 * "MedicationPrescription" or "MedicationOrder" to generalize the use across inpatient and
 * outpatient settings, including care plans, etc., and to harmonize with workflow patterns.
 *
 * Generated by Gallaware, Inc. from:
 *    file:/Users/admin/Documents/DevNetbeans/jsonSchemaToJava/target/classes/schema/fhir.schema.json#/definitions/MedicationRequest
 */
export class MedicationRequest {
  /**
   * This is a MedicationRequest resource
   */
     resourceType = "MedicationRequest";

  /**
   * Any combination of letters, numerals, "-" and ".", with a length limit of 64 characters.  (This
   * might be an integer, an unprefixed OID, UUID or any other identifier pattern that meets these
   * constraints.)  Ids are case-insensitive.
   * Field access restricted because there are specific valid values.
   */
  protected id?: string;

  /**
   * The metadata about a resource. This is content in the resource that is maintained by the
   * infrastructure. Changes to the content might not always be associated with version changes to the
   * resource.
   */
  @Type(() => Meta)
   meta?: Meta;

  /**
   * String of characters used to identify a name or a resource
   * Field access restricted because there are specific valid values.
   */
  protected implicitRules?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _implicitRules?: Element;

  /**
   * A string which has at least one character and no leading or trailing whitespace and where there is
   * no whitespace other than single spaces in the contents
   * Field access restricted because there are specific valid values.
   */
  protected language?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _language?: Element;

  /**
   * A human-readable summary of the resource conveying the essential clinical and business information
   * for the resource.
   */
  @Type(() => Narrative)
   text?: Narrative;

  /**
   * These resources do not have an independent existence apart from the resource that contains them -
   * they cannot be identified independently, and nor can they have their own independent transaction
   * scope.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => ResourceList, {
          discriminator: {
    property: 'resourceType',
    subTypes: [
      	{ value: Account, name: 'Account'},
      	{ value: ActivityDefinition, name: 'ActivityDefinition'},
      	{ value: AdverseEvent, name: 'AdverseEvent'},
      	{ value: AllergyIntolerance, name: 'AllergyIntolerance'},
      	{ value: Appointment, name: 'Appointment'},
      	{ value: AppointmentResponse, name: 'AppointmentResponse'},
      	{ value: AuditEvent, name: 'AuditEvent'},
      	{ value: Basic, name: 'Basic'},
      	{ value: Binary, name: 'Binary'},
      	{ value: BiologicallyDerivedProduct, name: 'BiologicallyDerivedProduct'},
      	{ value: BodyStructure, name: 'BodyStructure'},
      	{ value: Bundle, name: 'Bundle'},
      	{ value: CapabilityStatement, name: 'CapabilityStatement'},
      	{ value: CarePlan, name: 'CarePlan'},
      	{ value: CareTeam, name: 'CareTeam'},
      	{ value: CatalogEntry, name: 'CatalogEntry'},
      	{ value: ChargeItem, name: 'ChargeItem'},
      	{ value: ChargeItemDefinition, name: 'ChargeItemDefinition'},
      	{ value: Claim, name: 'Claim'},
      	{ value: ClaimResponse, name: 'ClaimResponse'},
      	{ value: ClinicalImpression, name: 'ClinicalImpression'},
      	{ value: CodeSystem, name: 'CodeSystem'},
      	{ value: Communication, name: 'Communication'},
      	{ value: CommunicationRequest, name: 'CommunicationRequest'},
      	{ value: CompartmentDefinition, name: 'CompartmentDefinition'},
      	{ value: Composition, name: 'Composition'},
      	{ value: ConceptMap, name: 'ConceptMap'},
      	{ value: Condition, name: 'Condition'},
      	{ value: Consent, name: 'Consent'},
      	{ value: Contract, name: 'Contract'},
      	{ value: Coverage, name: 'Coverage'},
      	{ value: CoverageEligibilityRequest, name: 'CoverageEligibilityRequest'},
      	{ value: CoverageEligibilityResponse, name: 'CoverageEligibilityResponse'},
      	{ value: DetectedIssue, name: 'DetectedIssue'},
      	{ value: Device, name: 'Device'},
      	{ value: DeviceDefinition, name: 'DeviceDefinition'},
      	{ value: DeviceMetric, name: 'DeviceMetric'},
      	{ value: DeviceRequest, name: 'DeviceRequest'},
      	{ value: DeviceUseStatement, name: 'DeviceUseStatement'},
      	{ value: DiagnosticReport, name: 'DiagnosticReport'},
      	{ value: DocumentManifest, name: 'DocumentManifest'},
      	{ value: DocumentReference, name: 'DocumentReference'},
      	{ value: EffectEvidenceSynthesis, name: 'EffectEvidenceSynthesis'},
      	{ value: Encounter, name: 'Encounter'},
      	{ value: Endpoint, name: 'Endpoint'},
      	{ value: EnrollmentRequest, name: 'EnrollmentRequest'},
      	{ value: EnrollmentResponse, name: 'EnrollmentResponse'},
      	{ value: EpisodeOfCare, name: 'EpisodeOfCare'},
      	{ value: EventDefinition, name: 'EventDefinition'},
      	{ value: Evidence, name: 'Evidence'},
      	{ value: EvidenceVariable, name: 'EvidenceVariable'},
      	{ value: ExampleScenario, name: 'ExampleScenario'},
      	{ value: ExplanationOfBenefit, name: 'ExplanationOfBenefit'},
      	{ value: FamilyMemberHistory, name: 'FamilyMemberHistory'},
      	{ value: Flag, name: 'Flag'},
      	{ value: Goal, name: 'Goal'},
      	{ value: GraphDefinition, name: 'GraphDefinition'},
      	{ value: Group, name: 'Group'},
      	{ value: GuidanceResponse, name: 'GuidanceResponse'},
      	{ value: HealthcareService, name: 'HealthcareService'},
      	{ value: ImagingStudy, name: 'ImagingStudy'},
      	{ value: Immunization, name: 'Immunization'},
      	{ value: ImmunizationEvaluation, name: 'ImmunizationEvaluation'},
      	{ value: ImmunizationRecommendation, name: 'ImmunizationRecommendation'},
      	{ value: ImplementationGuide, name: 'ImplementationGuide'},
      	{ value: InsurancePlan, name: 'InsurancePlan'},
      	{ value: Invoice, name: 'Invoice'},
      	{ value: Library, name: 'Library'},
      	{ value: Linkage, name: 'Linkage'},
      	{ value: List, name: 'List'},
      	{ value: Location, name: 'Location'},
      	{ value: Measure, name: 'Measure'},
      	{ value: MeasureReport, name: 'MeasureReport'},
      	{ value: Media, name: 'Media'},
      	{ value: Medication, name: 'Medication'},
      	{ value: MedicationAdministration, name: 'MedicationAdministration'},
      	{ value: MedicationDispense, name: 'MedicationDispense'},
      	{ value: MedicationKnowledge, name: 'MedicationKnowledge'},
      	{ value: MedicationRequest, name: 'MedicationRequest'},
      	{ value: MedicationStatement, name: 'MedicationStatement'},
      	{ value: MedicinalProduct, name: 'MedicinalProduct'},
      	{ value: MedicinalProductAuthorization, name: 'MedicinalProductAuthorization'},
      	{ value: MedicinalProductContraindication, name: 'MedicinalProductContraindication'},
      	{ value: MedicinalProductIndication, name: 'MedicinalProductIndication'},
      	{ value: MedicinalProductIngredient, name: 'MedicinalProductIngredient'},
      	{ value: MedicinalProductInteraction, name: 'MedicinalProductInteraction'},
      	{ value: MedicinalProductManufactured, name: 'MedicinalProductManufactured'},
      	{ value: MedicinalProductPackaged, name: 'MedicinalProductPackaged'},
      	{ value: MedicinalProductPharmaceutical, name: 'MedicinalProductPharmaceutical'},
      	{ value: MedicinalProductUndesirableEffect, name: 'MedicinalProductUndesirableEffect'},
      	{ value: MessageDefinition, name: 'MessageDefinition'},
      	{ value: MessageHeader, name: 'MessageHeader'},
      	{ value: MolecularSequence, name: 'MolecularSequence'},
      	{ value: NamingSystem, name: 'NamingSystem'},
      	{ value: NutritionOrder, name: 'NutritionOrder'},
      	{ value: Observation, name: 'Observation'},
      	{ value: ObservationDefinition, name: 'ObservationDefinition'},
      	{ value: OperationDefinition, name: 'OperationDefinition'},
      	{ value: OperationOutcome, name: 'OperationOutcome'},
      	{ value: Organization, name: 'Organization'},
      	{ value: OrganizationAffiliation, name: 'OrganizationAffiliation'},
      	{ value: Parameters, name: 'Parameters'},
      	{ value: Patient, name: 'Patient'},
      	{ value: PaymentNotice, name: 'PaymentNotice'},
      	{ value: PaymentReconciliation, name: 'PaymentReconciliation'},
      	{ value: Person, name: 'Person'},
      	{ value: PlanDefinition, name: 'PlanDefinition'},
      	{ value: Practitioner, name: 'Practitioner'},
      	{ value: PractitionerRole, name: 'PractitionerRole'},
      	{ value: Procedure, name: 'Procedure'},
      	{ value: Provenance, name: 'Provenance'},
      	{ value: Questionnaire, name: 'Questionnaire'},
      	{ value: QuestionnaireResponse, name: 'QuestionnaireResponse'},
      	{ value: RelatedPerson, name: 'RelatedPerson'},
      	{ value: RequestGroup, name: 'RequestGroup'},
      	{ value: ResearchDefinition, name: 'ResearchDefinition'},
      	{ value: ResearchElementDefinition, name: 'ResearchElementDefinition'},
      	{ value: ResearchStudy, name: 'ResearchStudy'},
      	{ value: ResearchSubject, name: 'ResearchSubject'},
      	{ value: RiskAssessment, name: 'RiskAssessment'},
      	{ value: RiskEvidenceSynthesis, name: 'RiskEvidenceSynthesis'},
      	{ value: Schedule, name: 'Schedule'},
      	{ value: SearchParameter, name: 'SearchParameter'},
      	{ value: ServiceRequest, name: 'ServiceRequest'},
      	{ value: Slot, name: 'Slot'},
      	{ value: Specimen, name: 'Specimen'},
      	{ value: SpecimenDefinition, name: 'SpecimenDefinition'},
      	{ value: StructureDefinition, name: 'StructureDefinition'},
      	{ value: StructureMap, name: 'StructureMap'},
      	{ value: Subscription, name: 'Subscription'},
      	{ value: Substance, name: 'Substance'},
      	{ value: SubstanceNucleicAcid, name: 'SubstanceNucleicAcid'},
      	{ value: SubstancePolymer, name: 'SubstancePolymer'},
      	{ value: SubstanceProtein, name: 'SubstanceProtein'},
      	{ value: SubstanceReferenceInformation, name: 'SubstanceReferenceInformation'},
      	{ value: SubstanceSourceMaterial, name: 'SubstanceSourceMaterial'},
      	{ value: SubstanceSpecification, name: 'SubstanceSpecification'},
      	{ value: SupplyDelivery, name: 'SupplyDelivery'},
      	{ value: SupplyRequest, name: 'SupplyRequest'},
      	{ value: Task, name: 'Task'},
      	{ value: TerminologyCapabilities, name: 'TerminologyCapabilities'},
      	{ value: TestReport, name: 'TestReport'},
      	{ value: TestScript, name: 'TestScript'},
      	{ value: ValueSet, name: 'ValueSet'},
      	{ value: VerificationResult, name: 'VerificationResult'},
      	{ value: VisionPrescription, name: 'VisionPrescription'}
      ],
    }
  })
  protected contained?: ResourceList[];

  /**
   * May be used to represent additional information that is not part of the basic definition of the
   * resource. To make the use of extensions safe and manageable, there is a strict set of governance
   * applied to the definition and use of extensions. Though any implementer can define an extension,
   * there is a set of requirements that SHALL be met as part of the definition of the extension.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Extension)
  protected extension?: Extension[];

  /**
   * May be used to represent additional information that is not part of the basic definition of the
   * resource and that modifies the understanding of the element that contains it and/or the
   * understanding of the containing element's descendants. Usually modifier elements provide negation
   * or qualification. To make the use of extensions safe and manageable, there is a strict set of
   * governance applied to the definition and use of extensions. Though any implementer is allowed to
   * define an extension, there is a set of requirements that SHALL be met as part of the definition of
   * the extension. Applications processing a resource are required to check for modifier extensions.
   * 
   * Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource
   * (including cannot change the meaning of modifierExtension itself).
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Extension)
  protected modifierExtension?: Extension[];

  /**
   * Identifiers associated with this medication request that are defined by business processes and/or
   * used to refer to it when a direct URL reference to the resource itself is not appropriate. They
   * are business identifiers assigned to this resource by the performer or other systems and remain
   * constant as the resource is updated and propagates from server to server.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Identifier)
  protected identifier?: Identifier[];

  /**
   * A string which has at least one character and no leading or trailing whitespace and where there is
   * no whitespace other than single spaces in the contents
   * Field access restricted because there are specific valid values.
   */
  protected status?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _status?: Element;

  /**
   * A concept that may be defined by a formal reference to a terminology or ontology or may be provided
   * by text.
   */
  @Type(() => CodeableConcept)
   statusReason?: CodeableConcept;

  /**
   * A string which has at least one character and no leading or trailing whitespace and where there is
   * no whitespace other than single spaces in the contents
   * Field access restricted because there are specific valid values.
   */
  protected intent?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _intent?: Element;

  /**
   * Indicates the type of medication request (for example, where the medication is expected to be
   * consumed or administered (i.e. inpatient or outpatient)).
   * Field access restricted because there are specific valid values.
   */
  @Type(() => CodeableConcept)
  protected category?: CodeableConcept[];

  /**
   * A string which has at least one character and no leading or trailing whitespace and where there is
   * no whitespace other than single spaces in the contents
   * Field access restricted because there are specific valid values.
   */
  protected priority?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _priority?: Element;

  /**
   * Value of "true" or "false"
   */
   doNotPerform?: boolean;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _doNotPerform?: Element;

  /**
   * Indicates if this record was captured as a secondary 'reported' record rather than as an original
   * primary source-of-truth record.  It may also indicate the source of the report.
   */
   reportedBoolean?: boolean;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _reportedBoolean?: Element;

  /**
   * A reference from one resource to another.
   */
  @Type(() => Reference)
   reportedReference?: Reference;

  /**
   * A concept that may be defined by a formal reference to a terminology or ontology or may be provided
   * by text.
   */
  @Type(() => CodeableConcept)
   medicationCodeableConcept?: CodeableConcept;

  /**
   * A reference from one resource to another.
   */
  @Type(() => Reference)
   medicationReference?: Reference;

  /**
   * A reference from one resource to another.
   */
  @Type(() => Reference)
   subject?: Reference;

  /**
   * A reference from one resource to another.
   */
  @Type(() => Reference)
   encounter?: Reference;

  /**
   * Include additional information (for example, patient height and weight) that supports the ordering
   * of the medication.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Reference)
  protected supportingInformation?: Reference[];

  /**
   * A date, date-time or partial date (e.g. just year or year + month).  If hours and minutes are
   * specified, a time zone SHALL be populated. The format is a union of the schema types gYear,
   * gYearMonth, date and dateTime. Seconds must be provided due to schema type constraints but may be
   * zero-filled and may be ignored.                 Dates SHALL be valid dates.
   * Field access restricted because there are specific valid values.
   */
  protected authoredOn?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _authoredOn?: Element;

  /**
   * A reference from one resource to another.
   */
  @Type(() => Reference)
   requester?: Reference;

  /**
   * A reference from one resource to another.
   */
  @Type(() => Reference)
   performer?: Reference;

  /**
   * A concept that may be defined by a formal reference to a terminology or ontology or may be provided
   * by text.
   */
  @Type(() => CodeableConcept)
   performerType?: CodeableConcept;

  /**
   * A reference from one resource to another.
   */
  @Type(() => Reference)
   recorder?: Reference;

  /**
   * The reason or the indication for ordering or not ordering the medication.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => CodeableConcept)
  protected reasonCode?: CodeableConcept[];

  /**
   * Condition or observation that supports why the medication was ordered.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Reference)
  protected reasonReference?: Reference[];

  /**
   * The URL pointing to a protocol, guideline, orderset, or other definition that is adhered to in
   * whole or in part by this MedicationRequest.
   * Field access restricted because there are specific valid values.
   */
  protected instantiatesCanonical?: string[];

  /**
   * Extensions for instantiatesCanonical
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Element)
  protected _instantiatesCanonical?: Element[];

  /**
   * The URL pointing to an externally maintained protocol, guideline, orderset or other definition that
   * is adhered to in whole or in part by this MedicationRequest.
   * Field access restricted because there are specific valid values.
   */
  protected instantiatesUri?: string[];

  /**
   * Extensions for instantiatesUri
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Element)
  protected _instantiatesUri?: Element[];

  /**
   * A plan or request that is fulfilled in whole or in part by this medication request.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Reference)
  protected basedOn?: Reference[];

  /**
   * An identifier - identifies some entity uniquely and unambiguously. Typically this is used for
   * business identifiers.
   */
  @Type(() => Identifier)
   groupIdentifier?: Identifier;

  /**
   * A concept that may be defined by a formal reference to a terminology or ontology or may be provided
   * by text.
   */
  @Type(() => CodeableConcept)
   courseOfTherapyType?: CodeableConcept;

  /**
   * Insurance plans, coverage extensions, pre-authorizations and/or pre-determinations that may be
   * required for delivering the requested service.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Reference)
  protected insurance?: Reference[];

  /**
   * Extra information about the prescription that could not be conveyed by the other attributes.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Annotation)
  protected note?: Annotation[];

  /**
   * Indicates how the medication is to be used by the patient.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Dosage)
  protected dosageInstruction?: Dosage[];

  /**
   * An order or request for both supply of the medication and the instructions for administration of
   * the medication to a patient. The resource is called "MedicationRequest" rather than
   * "MedicationPrescription" or "MedicationOrder" to generalize the use across inpatient and
   * outpatient settings, including care plans, etc., and to harmonize with workflow patterns.
   */
  @Type(() => MedicationRequestDispenseRequest)
   dispenseRequest?: MedicationRequestDispenseRequest;

  /**
   * An order or request for both supply of the medication and the instructions for administration of
   * the medication to a patient. The resource is called "MedicationRequest" rather than
   * "MedicationPrescription" or "MedicationOrder" to generalize the use across inpatient and
   * outpatient settings, including care plans, etc., and to harmonize with workflow patterns.
   */
  @Type(() => MedicationRequestSubstitution)
   substitution?: MedicationRequestSubstitution;

  /**
   * A reference from one resource to another.
   */
  @Type(() => Reference)
   priorPrescription?: Reference;

  /**
   * Indicates an actual or potential clinical issue with or between one or more active or proposed
   * clinical actions for a patient; e.g. Drug-drug interaction, duplicate therapy, dosage alert etc.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Reference)
  protected detectedIssue?: Reference[];

  /**
   * Links to Provenance records for past versions of this resource or fulfilling request or event
   * resources that identify key state transitions or updates that are likely to be relevant to a user
   * looking at the current version of the resource.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Reference)
  protected eventHistory?: Reference[];


  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setId(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.id) !== 'undefined') {
         delete this.id;
      }
      return;
    }
    
    if (REGEX_ID_000.test(newValue)) {
      this.id = newValue
    } else {
      throw new Error("Invalid value pattern for id of " + newValue);
    }
  }
  
  public getIdPattern(): string {
    return REGEX_ID_000.source;
  }
  
  /**
  * Gets the current value of field id.
  * @returns the value  or undefined
  */
  public getId(): string | undefined {
      return this.id;
  }

  /**
  * Gets the current value of field id if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getIdOrElse(defaultValue: string): string {
      if (this.id == undefined || this.id == null ) { return defaultValue; }
      return this.id;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setImplicitRules(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.implicitRules) !== 'undefined') {
         delete this.implicitRules;
      }
      return;
    }
    
    if (REGEX_IMPLICITRULES.test(newValue)) {
      this.implicitRules = newValue
    } else {
      throw new Error("Invalid value pattern for implicitRules of " + newValue);
    }
  }
  
  public getImplicitRulesPattern(): string {
    return REGEX_IMPLICITRULES.source;
  }
  
  /**
  * Gets the current value of field implicitRules.
  * @returns the value  or undefined
  */
  public getImplicitRules(): string | undefined {
      return this.implicitRules;
  }

  /**
  * Gets the current value of field implicitRules if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getImplicitRulesOrElse(defaultValue: string): string {
      if (this.implicitRules == undefined || this.implicitRules == null ) { return defaultValue; }
      return this.implicitRules;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setLanguage(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.language) !== 'undefined') {
         delete this.language;
      }
      return;
    }
    
    if (REGEX_LANGUAGE.test(newValue)) {
      this.language = newValue
    } else {
      throw new Error("Invalid value pattern for language of " + newValue);
    }
  }
  
  public getLanguagePattern(): string {
    return REGEX_LANGUAGE.source;
  }
  
  /**
  * Gets the current value of field language.
  * @returns the value  or undefined
  */
  public getLanguage(): string | undefined {
      return this.language;
  }

  /**
  * Gets the current value of field language if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getLanguageOrElse(defaultValue: string): string {
      if (this.language == undefined || this.language == null ) { return defaultValue; }
      return this.language;
  }

  public addContained(newValue: ResourceList) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.contained) !== 'undefined') {
         delete this.contained;
      }
      return;
    }
    
    if (typeof(this.contained) === 'undefined') {
      this.contained =  [];
    }
    this.contained.push(newValue);
  }
  /**
  * Removes all elements from the array contained, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteContainedAll(): ResourceList[] {
    if (typeof(this.contained) !== 'undefined') {
       const oldArray = this.contained;
       delete this.contained;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array contained, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteContainedBySplice(start: number, deleteCount?: number): ResourceList[] {
    if (typeof(this.contained) !== 'undefined') {
       return this.contained.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field contained.
  * @returns the value  or undefined
  */
  public getContained(): ResourceList[] | undefined {
      return this.contained;
  }

  /**
  * Gets the current value of field contained if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getContainedOrElse(defaultValue: ResourceList[]): ResourceList[] {
      if (this.contained == undefined || this.contained == null ) { return defaultValue; }
      return this.contained;
  }

  public addExtension(newValue: Extension) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.extension) !== 'undefined') {
         delete this.extension;
      }
      return;
    }
    
    if (typeof(this.extension) === 'undefined') {
      this.extension =  [];
    }
    this.extension.push(newValue);
  }
  /**
  * Removes all elements from the array extension, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteExtensionAll(): Extension[] {
    if (typeof(this.extension) !== 'undefined') {
       const oldArray = this.extension;
       delete this.extension;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array extension, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteExtensionBySplice(start: number, deleteCount?: number): Extension[] {
    if (typeof(this.extension) !== 'undefined') {
       return this.extension.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field extension.
  * @returns the value  or undefined
  */
  public getExtension(): Extension[] | undefined {
      return this.extension;
  }

  /**
  * Gets the current value of field extension if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getExtensionOrElse(defaultValue: Extension[]): Extension[] {
      if (this.extension == undefined || this.extension == null ) { return defaultValue; }
      return this.extension;
  }

  public addModifierExtension(newValue: Extension) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.modifierExtension) !== 'undefined') {
         delete this.modifierExtension;
      }
      return;
    }
    
    if (typeof(this.modifierExtension) === 'undefined') {
      this.modifierExtension =  [];
    }
    this.modifierExtension.push(newValue);
  }
  /**
  * Removes all elements from the array modifierExtension, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteModifierExtensionAll(): Extension[] {
    if (typeof(this.modifierExtension) !== 'undefined') {
       const oldArray = this.modifierExtension;
       delete this.modifierExtension;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array modifierExtension, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteModifierExtensionBySplice(start: number, deleteCount?: number): Extension[] {
    if (typeof(this.modifierExtension) !== 'undefined') {
       return this.modifierExtension.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field modifierExtension.
  * @returns the value  or undefined
  */
  public getModifierExtension(): Extension[] | undefined {
      return this.modifierExtension;
  }

  /**
  * Gets the current value of field modifierExtension if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getModifierExtensionOrElse(defaultValue: Extension[]): Extension[] {
      if (this.modifierExtension == undefined || this.modifierExtension == null ) { return defaultValue; }
      return this.modifierExtension;
  }

  public addIdentifier(newValue: Identifier) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.identifier) !== 'undefined') {
         delete this.identifier;
      }
      return;
    }
    
    if (typeof(this.identifier) === 'undefined') {
      this.identifier =  [];
    }
    this.identifier.push(newValue);
  }
  /**
  * Removes all elements from the array identifier, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteIdentifierAll(): Identifier[] {
    if (typeof(this.identifier) !== 'undefined') {
       const oldArray = this.identifier;
       delete this.identifier;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array identifier, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteIdentifierBySplice(start: number, deleteCount?: number): Identifier[] {
    if (typeof(this.identifier) !== 'undefined') {
       return this.identifier.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field identifier.
  * @returns the value  or undefined
  */
  public getIdentifier(): Identifier[] | undefined {
      return this.identifier;
  }

  /**
  * Gets the current value of field identifier if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getIdentifierOrElse(defaultValue: Identifier[]): Identifier[] {
      if (this.identifier == undefined || this.identifier == null ) { return defaultValue; }
      return this.identifier;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setStatus(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.status) !== 'undefined') {
         delete this.status;
      }
      return;
    }
    
    if (REGEX_STATUS_000.test(newValue)) {
      this.status = newValue
    } else {
      throw new Error("Invalid value pattern for status of " + newValue);
    }
  }
  
  public getStatusPattern(): string {
    return REGEX_STATUS_000.source;
  }
  
  /**
  * Gets the current value of field status.
  * @returns the value  or undefined
  */
  public getStatus(): string | undefined {
      return this.status;
  }

  /**
  * Gets the current value of field status if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getStatusOrElse(defaultValue: string): string {
      if (this.status == undefined || this.status == null ) { return defaultValue; }
      return this.status;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setIntent(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.intent) !== 'undefined') {
         delete this.intent;
      }
      return;
    }
    
    if (REGEX_INTENT.test(newValue)) {
      this.intent = newValue
    } else {
      throw new Error("Invalid value pattern for intent of " + newValue);
    }
  }
  
  public getIntentPattern(): string {
    return REGEX_INTENT.source;
  }
  
  /**
  * Gets the current value of field intent.
  * @returns the value  or undefined
  */
  public getIntent(): string | undefined {
      return this.intent;
  }

  /**
  * Gets the current value of field intent if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getIntentOrElse(defaultValue: string): string {
      if (this.intent == undefined || this.intent == null ) { return defaultValue; }
      return this.intent;
  }

  public addCategory(newValue: CodeableConcept) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.category) !== 'undefined') {
         delete this.category;
      }
      return;
    }
    
    if (typeof(this.category) === 'undefined') {
      this.category =  [];
    }
    this.category.push(newValue);
  }
  /**
  * Removes all elements from the array category, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteCategoryAll(): CodeableConcept[] {
    if (typeof(this.category) !== 'undefined') {
       const oldArray = this.category;
       delete this.category;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array category, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteCategoryBySplice(start: number, deleteCount?: number): CodeableConcept[] {
    if (typeof(this.category) !== 'undefined') {
       return this.category.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field category.
  * @returns the value  or undefined
  */
  public getCategory(): CodeableConcept[] | undefined {
      return this.category;
  }

  /**
  * Gets the current value of field category if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getCategoryOrElse(defaultValue: CodeableConcept[]): CodeableConcept[] {
      if (this.category == undefined || this.category == null ) { return defaultValue; }
      return this.category;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setPriority(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.priority) !== 'undefined') {
         delete this.priority;
      }
      return;
    }
    
    if (REGEX_PRIORITY.test(newValue)) {
      this.priority = newValue
    } else {
      throw new Error("Invalid value pattern for priority of " + newValue);
    }
  }
  
  public getPriorityPattern(): string {
    return REGEX_PRIORITY.source;
  }
  
  /**
  * Gets the current value of field priority.
  * @returns the value  or undefined
  */
  public getPriority(): string | undefined {
      return this.priority;
  }

  /**
  * Gets the current value of field priority if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getPriorityOrElse(defaultValue: string): string {
      if (this.priority == undefined || this.priority == null ) { return defaultValue; }
      return this.priority;
  }

  public addSupportingInformation(newValue: Reference) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.supportingInformation) !== 'undefined') {
         delete this.supportingInformation;
      }
      return;
    }
    
    if (typeof(this.supportingInformation) === 'undefined') {
      this.supportingInformation =  [];
    }
    this.supportingInformation.push(newValue);
  }
  /**
  * Removes all elements from the array supportingInformation, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteSupportingInformationAll(): Reference[] {
    if (typeof(this.supportingInformation) !== 'undefined') {
       const oldArray = this.supportingInformation;
       delete this.supportingInformation;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array supportingInformation, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteSupportingInformationBySplice(start: number, deleteCount?: number): Reference[] {
    if (typeof(this.supportingInformation) !== 'undefined') {
       return this.supportingInformation.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field supportingInformation.
  * @returns the value  or undefined
  */
  public getSupportingInformation(): Reference[] | undefined {
      return this.supportingInformation;
  }

  /**
  * Gets the current value of field supportingInformation if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getSupportingInformationOrElse(defaultValue: Reference[]): Reference[] {
      if (this.supportingInformation == undefined || this.supportingInformation == null ) { return defaultValue; }
      return this.supportingInformation;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setAuthoredOn(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.authoredOn) !== 'undefined') {
         delete this.authoredOn;
      }
      return;
    }
    
    if (REGEX_AUTHOREDON.test(newValue)) {
      this.authoredOn = newValue
    } else {
      throw new Error("Invalid value pattern for authoredOn of " + newValue);
    }
  }
  
  public getAuthoredOnPattern(): string {
    return REGEX_AUTHOREDON.source;
  }
  
  /**
  * Gets the current value of field authoredOn.
  * @returns the value  or undefined
  */
  public getAuthoredOn(): string | undefined {
      return this.authoredOn;
  }

  /**
  * Gets the current value of field authoredOn if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getAuthoredOnOrElse(defaultValue: string): string {
      if (this.authoredOn == undefined || this.authoredOn == null ) { return defaultValue; }
      return this.authoredOn;
  }

  public addReasonCode(newValue: CodeableConcept) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.reasonCode) !== 'undefined') {
         delete this.reasonCode;
      }
      return;
    }
    
    if (typeof(this.reasonCode) === 'undefined') {
      this.reasonCode =  [];
    }
    this.reasonCode.push(newValue);
  }
  /**
  * Removes all elements from the array reasonCode, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteReasonCodeAll(): CodeableConcept[] {
    if (typeof(this.reasonCode) !== 'undefined') {
       const oldArray = this.reasonCode;
       delete this.reasonCode;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array reasonCode, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteReasonCodeBySplice(start: number, deleteCount?: number): CodeableConcept[] {
    if (typeof(this.reasonCode) !== 'undefined') {
       return this.reasonCode.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field reasonCode.
  * @returns the value  or undefined
  */
  public getReasonCode(): CodeableConcept[] | undefined {
      return this.reasonCode;
  }

  /**
  * Gets the current value of field reasonCode if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getReasonCodeOrElse(defaultValue: CodeableConcept[]): CodeableConcept[] {
      if (this.reasonCode == undefined || this.reasonCode == null ) { return defaultValue; }
      return this.reasonCode;
  }

  public addReasonReference(newValue: Reference) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.reasonReference) !== 'undefined') {
         delete this.reasonReference;
      }
      return;
    }
    
    if (typeof(this.reasonReference) === 'undefined') {
      this.reasonReference =  [];
    }
    this.reasonReference.push(newValue);
  }
  /**
  * Removes all elements from the array reasonReference, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteReasonReferenceAll(): Reference[] {
    if (typeof(this.reasonReference) !== 'undefined') {
       const oldArray = this.reasonReference;
       delete this.reasonReference;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array reasonReference, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteReasonReferenceBySplice(start: number, deleteCount?: number): Reference[] {
    if (typeof(this.reasonReference) !== 'undefined') {
       return this.reasonReference.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field reasonReference.
  * @returns the value  or undefined
  */
  public getReasonReference(): Reference[] | undefined {
      return this.reasonReference;
  }

  /**
  * Gets the current value of field reasonReference if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getReasonReferenceOrElse(defaultValue: Reference[]): Reference[] {
      if (this.reasonReference == undefined || this.reasonReference == null ) { return defaultValue; }
      return this.reasonReference;
  }

  public addInstantiatesCanonical(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.instantiatesCanonical) !== 'undefined') {
         delete this.instantiatesCanonical;
      }
      return;
    }
    
    if (typeof(this.instantiatesCanonical) === 'undefined') {
      this.instantiatesCanonical =  [];
    }
    this.instantiatesCanonical.push(newValue);
  }
  /**
  * Removes all elements from the array instantiatesCanonical, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteInstantiatesCanonicalAll(): string[] {
    if (typeof(this.instantiatesCanonical) !== 'undefined') {
       const oldArray = this.instantiatesCanonical;
       delete this.instantiatesCanonical;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array instantiatesCanonical, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteInstantiatesCanonicalBySplice(start: number, deleteCount?: number): string[] {
    if (typeof(this.instantiatesCanonical) !== 'undefined') {
       return this.instantiatesCanonical.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field instantiatesCanonical.
  * @returns the value  or undefined
  */
  public getInstantiatesCanonical(): string[] | undefined {
      return this.instantiatesCanonical;
  }

  /**
  * Gets the current value of field instantiatesCanonical if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getInstantiatesCanonicalOrElse(defaultValue: string[]): string[] {
      if (this.instantiatesCanonical == undefined || this.instantiatesCanonical == null ) { return defaultValue; }
      return this.instantiatesCanonical;
  }

  public add_instantiatesCanonical(newValue: Element) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this._instantiatesCanonical) !== 'undefined') {
         delete this._instantiatesCanonical;
      }
      return;
    }
    
    if (typeof(this._instantiatesCanonical) === 'undefined') {
      this._instantiatesCanonical =  [];
    }
    this._instantiatesCanonical.push(newValue);
  }
  /**
  * Removes all elements from the array _instantiatesCanonical, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public delete_instantiatesCanonicalAll(): Element[] {
    if (typeof(this._instantiatesCanonical) !== 'undefined') {
       const oldArray = this._instantiatesCanonical;
       delete this._instantiatesCanonical;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array _instantiatesCanonical, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public delete_instantiatesCanonicalBySplice(start: number, deleteCount?: number): Element[] {
    if (typeof(this._instantiatesCanonical) !== 'undefined') {
       return this._instantiatesCanonical.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field _instantiatesCanonical.
  * @returns the value  or undefined
  */
  public get_instantiatesCanonical(): Element[] | undefined {
      return this._instantiatesCanonical;
  }

  /**
  * Gets the current value of field _instantiatesCanonical if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public get_instantiatesCanonicalOrElse(defaultValue: Element[]): Element[] {
      if (this._instantiatesCanonical == undefined || this._instantiatesCanonical == null ) { return defaultValue; }
      return this._instantiatesCanonical;
  }

  public addInstantiatesUri(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.instantiatesUri) !== 'undefined') {
         delete this.instantiatesUri;
      }
      return;
    }
    
    if (typeof(this.instantiatesUri) === 'undefined') {
      this.instantiatesUri =  [];
    }
    this.instantiatesUri.push(newValue);
  }
  /**
  * Removes all elements from the array instantiatesUri, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteInstantiatesUriAll(): string[] {
    if (typeof(this.instantiatesUri) !== 'undefined') {
       const oldArray = this.instantiatesUri;
       delete this.instantiatesUri;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array instantiatesUri, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteInstantiatesUriBySplice(start: number, deleteCount?: number): string[] {
    if (typeof(this.instantiatesUri) !== 'undefined') {
       return this.instantiatesUri.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field instantiatesUri.
  * @returns the value  or undefined
  */
  public getInstantiatesUri(): string[] | undefined {
      return this.instantiatesUri;
  }

  /**
  * Gets the current value of field instantiatesUri if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getInstantiatesUriOrElse(defaultValue: string[]): string[] {
      if (this.instantiatesUri == undefined || this.instantiatesUri == null ) { return defaultValue; }
      return this.instantiatesUri;
  }

  public add_instantiatesUri(newValue: Element) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this._instantiatesUri) !== 'undefined') {
         delete this._instantiatesUri;
      }
      return;
    }
    
    if (typeof(this._instantiatesUri) === 'undefined') {
      this._instantiatesUri =  [];
    }
    this._instantiatesUri.push(newValue);
  }
  /**
  * Removes all elements from the array _instantiatesUri, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public delete_instantiatesUriAll(): Element[] {
    if (typeof(this._instantiatesUri) !== 'undefined') {
       const oldArray = this._instantiatesUri;
       delete this._instantiatesUri;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array _instantiatesUri, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public delete_instantiatesUriBySplice(start: number, deleteCount?: number): Element[] {
    if (typeof(this._instantiatesUri) !== 'undefined') {
       return this._instantiatesUri.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field _instantiatesUri.
  * @returns the value  or undefined
  */
  public get_instantiatesUri(): Element[] | undefined {
      return this._instantiatesUri;
  }

  /**
  * Gets the current value of field _instantiatesUri if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public get_instantiatesUriOrElse(defaultValue: Element[]): Element[] {
      if (this._instantiatesUri == undefined || this._instantiatesUri == null ) { return defaultValue; }
      return this._instantiatesUri;
  }

  public addBasedOn(newValue: Reference) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.basedOn) !== 'undefined') {
         delete this.basedOn;
      }
      return;
    }
    
    if (typeof(this.basedOn) === 'undefined') {
      this.basedOn =  [];
    }
    this.basedOn.push(newValue);
  }
  /**
  * Removes all elements from the array basedOn, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteBasedOnAll(): Reference[] {
    if (typeof(this.basedOn) !== 'undefined') {
       const oldArray = this.basedOn;
       delete this.basedOn;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array basedOn, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteBasedOnBySplice(start: number, deleteCount?: number): Reference[] {
    if (typeof(this.basedOn) !== 'undefined') {
       return this.basedOn.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field basedOn.
  * @returns the value  or undefined
  */
  public getBasedOn(): Reference[] | undefined {
      return this.basedOn;
  }

  /**
  * Gets the current value of field basedOn if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getBasedOnOrElse(defaultValue: Reference[]): Reference[] {
      if (this.basedOn == undefined || this.basedOn == null ) { return defaultValue; }
      return this.basedOn;
  }

  public addInsurance(newValue: Reference) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.insurance) !== 'undefined') {
         delete this.insurance;
      }
      return;
    }
    
    if (typeof(this.insurance) === 'undefined') {
      this.insurance =  [];
    }
    this.insurance.push(newValue);
  }
  /**
  * Removes all elements from the array insurance, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteInsuranceAll(): Reference[] {
    if (typeof(this.insurance) !== 'undefined') {
       const oldArray = this.insurance;
       delete this.insurance;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array insurance, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteInsuranceBySplice(start: number, deleteCount?: number): Reference[] {
    if (typeof(this.insurance) !== 'undefined') {
       return this.insurance.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field insurance.
  * @returns the value  or undefined
  */
  public getInsurance(): Reference[] | undefined {
      return this.insurance;
  }

  /**
  * Gets the current value of field insurance if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getInsuranceOrElse(defaultValue: Reference[]): Reference[] {
      if (this.insurance == undefined || this.insurance == null ) { return defaultValue; }
      return this.insurance;
  }

  public addNote(newValue: Annotation) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.note) !== 'undefined') {
         delete this.note;
      }
      return;
    }
    
    if (typeof(this.note) === 'undefined') {
      this.note =  [];
    }
    this.note.push(newValue);
  }
  /**
  * Removes all elements from the array note, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteNoteAll(): Annotation[] {
    if (typeof(this.note) !== 'undefined') {
       const oldArray = this.note;
       delete this.note;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array note, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteNoteBySplice(start: number, deleteCount?: number): Annotation[] {
    if (typeof(this.note) !== 'undefined') {
       return this.note.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field note.
  * @returns the value  or undefined
  */
  public getNote(): Annotation[] | undefined {
      return this.note;
  }

  /**
  * Gets the current value of field note if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getNoteOrElse(defaultValue: Annotation[]): Annotation[] {
      if (this.note == undefined || this.note == null ) { return defaultValue; }
      return this.note;
  }

  public addDosageInstruction(newValue: Dosage) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.dosageInstruction) !== 'undefined') {
         delete this.dosageInstruction;
      }
      return;
    }
    
    if (typeof(this.dosageInstruction) === 'undefined') {
      this.dosageInstruction =  [];
    }
    this.dosageInstruction.push(newValue);
  }
  /**
  * Removes all elements from the array dosageInstruction, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteDosageInstructionAll(): Dosage[] {
    if (typeof(this.dosageInstruction) !== 'undefined') {
       const oldArray = this.dosageInstruction;
       delete this.dosageInstruction;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array dosageInstruction, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteDosageInstructionBySplice(start: number, deleteCount?: number): Dosage[] {
    if (typeof(this.dosageInstruction) !== 'undefined') {
       return this.dosageInstruction.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field dosageInstruction.
  * @returns the value  or undefined
  */
  public getDosageInstruction(): Dosage[] | undefined {
      return this.dosageInstruction;
  }

  /**
  * Gets the current value of field dosageInstruction if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getDosageInstructionOrElse(defaultValue: Dosage[]): Dosage[] {
      if (this.dosageInstruction == undefined || this.dosageInstruction == null ) { return defaultValue; }
      return this.dosageInstruction;
  }

  public addDetectedIssue(newValue: Reference) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.detectedIssue) !== 'undefined') {
         delete this.detectedIssue;
      }
      return;
    }
    
    if (typeof(this.detectedIssue) === 'undefined') {
      this.detectedIssue =  [];
    }
    this.detectedIssue.push(newValue);
  }
  /**
  * Removes all elements from the array detectedIssue, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteDetectedIssueAll(): Reference[] {
    if (typeof(this.detectedIssue) !== 'undefined') {
       const oldArray = this.detectedIssue;
       delete this.detectedIssue;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array detectedIssue, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteDetectedIssueBySplice(start: number, deleteCount?: number): Reference[] {
    if (typeof(this.detectedIssue) !== 'undefined') {
       return this.detectedIssue.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field detectedIssue.
  * @returns the value  or undefined
  */
  public getDetectedIssue(): Reference[] | undefined {
      return this.detectedIssue;
  }

  /**
  * Gets the current value of field detectedIssue if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getDetectedIssueOrElse(defaultValue: Reference[]): Reference[] {
      if (this.detectedIssue == undefined || this.detectedIssue == null ) { return defaultValue; }
      return this.detectedIssue;
  }

  public addEventHistory(newValue: Reference) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.eventHistory) !== 'undefined') {
         delete this.eventHistory;
      }
      return;
    }
    
    if (typeof(this.eventHistory) === 'undefined') {
      this.eventHistory =  [];
    }
    this.eventHistory.push(newValue);
  }
  /**
  * Removes all elements from the array eventHistory, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteEventHistoryAll(): Reference[] {
    if (typeof(this.eventHistory) !== 'undefined') {
       const oldArray = this.eventHistory;
       delete this.eventHistory;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array eventHistory, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteEventHistoryBySplice(start: number, deleteCount?: number): Reference[] {
    if (typeof(this.eventHistory) !== 'undefined') {
       return this.eventHistory.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field eventHistory.
  * @returns the value  or undefined
  */
  public getEventHistory(): Reference[] | undefined {
      return this.eventHistory;
  }

  /**
  * Gets the current value of field eventHistory if it exists,
  * but if it is 'undefined' it will return the value supplied
  * as the parameter.
  * @returns the value or the parameter value
  */
  public getEventHistoryOrElse(defaultValue: Reference[]): Reference[] {
      if (this.eventHistory == undefined || this.eventHistory == null ) { return defaultValue; }
      return this.eventHistory;
  }


}


