import { Type } from 'class-transformer';
import { REGEX_ID_000, REGEX_IMPLICITRULES, REGEX_LANGUAGE, REGEX_STATUS_000, REGEX_PREPARATIONINSTRUCTION } from '../FhirTsLibValidation/FhirRegex';
import { CodeableConcept, Element, Extension, MedicationKnowledgeAdministrationGuidelines, MedicationKnowledgeCost, MedicationKnowledgeDrugCharacteristic, MedicationKnowledgeIngredient, MedicationKnowledgeKinetics, MedicationKnowledgeMedicineClassification, MedicationKnowledgeMonitoringProgram, MedicationKnowledgeMonograph, MedicationKnowledgePackaging, MedicationKnowledgeRegulatory, MedicationKnowledgeRelatedMedicationKnowledge, Meta, Narrative, Quantity, Reference, ResourceList, Account, ActivityDefinition, AdverseEvent, AllergyIntolerance, Appointment, AppointmentResponse, AuditEvent, Basic, Binary, BiologicallyDerivedProduct, BodyStructure, Bundle, CapabilityStatement, CarePlan, CareTeam, CatalogEntry, ChargeItem, ChargeItemDefinition, Claim, ClaimResponse, ClinicalImpression, CodeSystem, Communication, CommunicationRequest, CompartmentDefinition, Composition, ConceptMap, Condition, Consent, Contract, Coverage, CoverageEligibilityRequest, CoverageEligibilityResponse, DetectedIssue, Device, DeviceDefinition, DeviceMetric, DeviceRequest, DeviceUseStatement, DiagnosticReport, DocumentManifest, DocumentReference, EffectEvidenceSynthesis, Encounter, Endpoint, EnrollmentRequest, EnrollmentResponse, EpisodeOfCare, EventDefinition, Evidence, EvidenceVariable, ExampleScenario, ExplanationOfBenefit, FamilyMemberHistory, Flag, Goal, GraphDefinition, Group, GuidanceResponse, HealthcareService, ImagingStudy, Immunization, ImmunizationEvaluation, ImmunizationRecommendation, ImplementationGuide, InsurancePlan, Invoice, Library, Linkage, List, Location, Measure, MeasureReport, Media, Medication, MedicationAdministration, MedicationDispense, MedicationRequest, MedicationStatement, MedicinalProduct, MedicinalProductAuthorization, MedicinalProductContraindication, MedicinalProductIndication, MedicinalProductIngredient, MedicinalProductInteraction, MedicinalProductManufactured, MedicinalProductPackaged, MedicinalProductPharmaceutical, MedicinalProductUndesirableEffect, MessageDefinition, MessageHeader, MolecularSequence, NamingSystem, NutritionOrder, Observation, ObservationDefinition, OperationDefinition, OperationOutcome, Organization, OrganizationAffiliation, Parameters, Patient, PaymentNotice, PaymentReconciliation, Person, PlanDefinition, Practitioner, PractitionerRole, Procedure, Provenance, Questionnaire, QuestionnaireResponse, RelatedPerson, RequestGroup, ResearchDefinition, ResearchElementDefinition, ResearchStudy, ResearchSubject, RiskAssessment, RiskEvidenceSynthesis, Schedule, SearchParameter, ServiceRequest, Slot, Specimen, SpecimenDefinition, StructureDefinition, StructureMap, Subscription, Substance, SubstanceNucleicAcid, SubstancePolymer, SubstanceProtein, SubstanceReferenceInformation, SubstanceSourceMaterial, SubstanceSpecification, SupplyDelivery, SupplyRequest, Task, TerminologyCapabilities, TestReport, TestScript, ValueSet, VerificationResult, VisionPrescription } from './index';



/**
 * Information about a medication that is used to support knowledge.
 *
 * Generated by Gallaware, Inc. from:
 *    file:/Users/admin/Documents/DevNetbeans/jsonSchemaToJava/target/classes/schema/fhir.schema.json#/definitions/MedicationKnowledge
 */
export class MedicationKnowledge {
  /**
   * This is a MedicationKnowledge resource
   */
     resourceType = "MedicationKnowledge";

  /**
   * Any combination of letters, numerals, "-" and ".", with a length limit of 64 characters.  (This
   * might be an integer, an unprefixed OID, UUID or any other identifier pattern that meets these
   * constraints.)  Ids are case-insensitive.
   * Field access restricted because there are specific valid values.
   */
  protected id?: string;

  /**
   * The metadata about a resource. This is content in the resource that is maintained by the
   * infrastructure. Changes to the content might not always be associated with version changes to the
   * resource.
   */
  @Type(() => Meta)
   meta?: Meta;

  /**
   * String of characters used to identify a name or a resource
   * Field access restricted because there are specific valid values.
   */
  protected implicitRules?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _implicitRules?: Element;

  /**
   * A string which has at least one character and no leading or trailing whitespace and where there is
   * no whitespace other than single spaces in the contents
   * Field access restricted because there are specific valid values.
   */
  protected language?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _language?: Element;

  /**
   * A human-readable summary of the resource conveying the essential clinical and business information
   * for the resource.
   */
  @Type(() => Narrative)
   text?: Narrative;

  /**
   * These resources do not have an independent existence apart from the resource that contains them -
   * they cannot be identified independently, and nor can they have their own independent transaction
   * scope.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => ResourceList, {
          discriminator: {
    property: 'resourceType',
    subTypes: [
      	{ value: Account, name: 'Account'},
      	{ value: ActivityDefinition, name: 'ActivityDefinition'},
      	{ value: AdverseEvent, name: 'AdverseEvent'},
      	{ value: AllergyIntolerance, name: 'AllergyIntolerance'},
      	{ value: Appointment, name: 'Appointment'},
      	{ value: AppointmentResponse, name: 'AppointmentResponse'},
      	{ value: AuditEvent, name: 'AuditEvent'},
      	{ value: Basic, name: 'Basic'},
      	{ value: Binary, name: 'Binary'},
      	{ value: BiologicallyDerivedProduct, name: 'BiologicallyDerivedProduct'},
      	{ value: BodyStructure, name: 'BodyStructure'},
      	{ value: Bundle, name: 'Bundle'},
      	{ value: CapabilityStatement, name: 'CapabilityStatement'},
      	{ value: CarePlan, name: 'CarePlan'},
      	{ value: CareTeam, name: 'CareTeam'},
      	{ value: CatalogEntry, name: 'CatalogEntry'},
      	{ value: ChargeItem, name: 'ChargeItem'},
      	{ value: ChargeItemDefinition, name: 'ChargeItemDefinition'},
      	{ value: Claim, name: 'Claim'},
      	{ value: ClaimResponse, name: 'ClaimResponse'},
      	{ value: ClinicalImpression, name: 'ClinicalImpression'},
      	{ value: CodeSystem, name: 'CodeSystem'},
      	{ value: Communication, name: 'Communication'},
      	{ value: CommunicationRequest, name: 'CommunicationRequest'},
      	{ value: CompartmentDefinition, name: 'CompartmentDefinition'},
      	{ value: Composition, name: 'Composition'},
      	{ value: ConceptMap, name: 'ConceptMap'},
      	{ value: Condition, name: 'Condition'},
      	{ value: Consent, name: 'Consent'},
      	{ value: Contract, name: 'Contract'},
      	{ value: Coverage, name: 'Coverage'},
      	{ value: CoverageEligibilityRequest, name: 'CoverageEligibilityRequest'},
      	{ value: CoverageEligibilityResponse, name: 'CoverageEligibilityResponse'},
      	{ value: DetectedIssue, name: 'DetectedIssue'},
      	{ value: Device, name: 'Device'},
      	{ value: DeviceDefinition, name: 'DeviceDefinition'},
      	{ value: DeviceMetric, name: 'DeviceMetric'},
      	{ value: DeviceRequest, name: 'DeviceRequest'},
      	{ value: DeviceUseStatement, name: 'DeviceUseStatement'},
      	{ value: DiagnosticReport, name: 'DiagnosticReport'},
      	{ value: DocumentManifest, name: 'DocumentManifest'},
      	{ value: DocumentReference, name: 'DocumentReference'},
      	{ value: EffectEvidenceSynthesis, name: 'EffectEvidenceSynthesis'},
      	{ value: Encounter, name: 'Encounter'},
      	{ value: Endpoint, name: 'Endpoint'},
      	{ value: EnrollmentRequest, name: 'EnrollmentRequest'},
      	{ value: EnrollmentResponse, name: 'EnrollmentResponse'},
      	{ value: EpisodeOfCare, name: 'EpisodeOfCare'},
      	{ value: EventDefinition, name: 'EventDefinition'},
      	{ value: Evidence, name: 'Evidence'},
      	{ value: EvidenceVariable, name: 'EvidenceVariable'},
      	{ value: ExampleScenario, name: 'ExampleScenario'},
      	{ value: ExplanationOfBenefit, name: 'ExplanationOfBenefit'},
      	{ value: FamilyMemberHistory, name: 'FamilyMemberHistory'},
      	{ value: Flag, name: 'Flag'},
      	{ value: Goal, name: 'Goal'},
      	{ value: GraphDefinition, name: 'GraphDefinition'},
      	{ value: Group, name: 'Group'},
      	{ value: GuidanceResponse, name: 'GuidanceResponse'},
      	{ value: HealthcareService, name: 'HealthcareService'},
      	{ value: ImagingStudy, name: 'ImagingStudy'},
      	{ value: Immunization, name: 'Immunization'},
      	{ value: ImmunizationEvaluation, name: 'ImmunizationEvaluation'},
      	{ value: ImmunizationRecommendation, name: 'ImmunizationRecommendation'},
      	{ value: ImplementationGuide, name: 'ImplementationGuide'},
      	{ value: InsurancePlan, name: 'InsurancePlan'},
      	{ value: Invoice, name: 'Invoice'},
      	{ value: Library, name: 'Library'},
      	{ value: Linkage, name: 'Linkage'},
      	{ value: List, name: 'List'},
      	{ value: Location, name: 'Location'},
      	{ value: Measure, name: 'Measure'},
      	{ value: MeasureReport, name: 'MeasureReport'},
      	{ value: Media, name: 'Media'},
      	{ value: Medication, name: 'Medication'},
      	{ value: MedicationAdministration, name: 'MedicationAdministration'},
      	{ value: MedicationDispense, name: 'MedicationDispense'},
      	{ value: MedicationKnowledge, name: 'MedicationKnowledge'},
      	{ value: MedicationRequest, name: 'MedicationRequest'},
      	{ value: MedicationStatement, name: 'MedicationStatement'},
      	{ value: MedicinalProduct, name: 'MedicinalProduct'},
      	{ value: MedicinalProductAuthorization, name: 'MedicinalProductAuthorization'},
      	{ value: MedicinalProductContraindication, name: 'MedicinalProductContraindication'},
      	{ value: MedicinalProductIndication, name: 'MedicinalProductIndication'},
      	{ value: MedicinalProductIngredient, name: 'MedicinalProductIngredient'},
      	{ value: MedicinalProductInteraction, name: 'MedicinalProductInteraction'},
      	{ value: MedicinalProductManufactured, name: 'MedicinalProductManufactured'},
      	{ value: MedicinalProductPackaged, name: 'MedicinalProductPackaged'},
      	{ value: MedicinalProductPharmaceutical, name: 'MedicinalProductPharmaceutical'},
      	{ value: MedicinalProductUndesirableEffect, name: 'MedicinalProductUndesirableEffect'},
      	{ value: MessageDefinition, name: 'MessageDefinition'},
      	{ value: MessageHeader, name: 'MessageHeader'},
      	{ value: MolecularSequence, name: 'MolecularSequence'},
      	{ value: NamingSystem, name: 'NamingSystem'},
      	{ value: NutritionOrder, name: 'NutritionOrder'},
      	{ value: Observation, name: 'Observation'},
      	{ value: ObservationDefinition, name: 'ObservationDefinition'},
      	{ value: OperationDefinition, name: 'OperationDefinition'},
      	{ value: OperationOutcome, name: 'OperationOutcome'},
      	{ value: Organization, name: 'Organization'},
      	{ value: OrganizationAffiliation, name: 'OrganizationAffiliation'},
      	{ value: Parameters, name: 'Parameters'},
      	{ value: Patient, name: 'Patient'},
      	{ value: PaymentNotice, name: 'PaymentNotice'},
      	{ value: PaymentReconciliation, name: 'PaymentReconciliation'},
      	{ value: Person, name: 'Person'},
      	{ value: PlanDefinition, name: 'PlanDefinition'},
      	{ value: Practitioner, name: 'Practitioner'},
      	{ value: PractitionerRole, name: 'PractitionerRole'},
      	{ value: Procedure, name: 'Procedure'},
      	{ value: Provenance, name: 'Provenance'},
      	{ value: Questionnaire, name: 'Questionnaire'},
      	{ value: QuestionnaireResponse, name: 'QuestionnaireResponse'},
      	{ value: RelatedPerson, name: 'RelatedPerson'},
      	{ value: RequestGroup, name: 'RequestGroup'},
      	{ value: ResearchDefinition, name: 'ResearchDefinition'},
      	{ value: ResearchElementDefinition, name: 'ResearchElementDefinition'},
      	{ value: ResearchStudy, name: 'ResearchStudy'},
      	{ value: ResearchSubject, name: 'ResearchSubject'},
      	{ value: RiskAssessment, name: 'RiskAssessment'},
      	{ value: RiskEvidenceSynthesis, name: 'RiskEvidenceSynthesis'},
      	{ value: Schedule, name: 'Schedule'},
      	{ value: SearchParameter, name: 'SearchParameter'},
      	{ value: ServiceRequest, name: 'ServiceRequest'},
      	{ value: Slot, name: 'Slot'},
      	{ value: Specimen, name: 'Specimen'},
      	{ value: SpecimenDefinition, name: 'SpecimenDefinition'},
      	{ value: StructureDefinition, name: 'StructureDefinition'},
      	{ value: StructureMap, name: 'StructureMap'},
      	{ value: Subscription, name: 'Subscription'},
      	{ value: Substance, name: 'Substance'},
      	{ value: SubstanceNucleicAcid, name: 'SubstanceNucleicAcid'},
      	{ value: SubstancePolymer, name: 'SubstancePolymer'},
      	{ value: SubstanceProtein, name: 'SubstanceProtein'},
      	{ value: SubstanceReferenceInformation, name: 'SubstanceReferenceInformation'},
      	{ value: SubstanceSourceMaterial, name: 'SubstanceSourceMaterial'},
      	{ value: SubstanceSpecification, name: 'SubstanceSpecification'},
      	{ value: SupplyDelivery, name: 'SupplyDelivery'},
      	{ value: SupplyRequest, name: 'SupplyRequest'},
      	{ value: Task, name: 'Task'},
      	{ value: TerminologyCapabilities, name: 'TerminologyCapabilities'},
      	{ value: TestReport, name: 'TestReport'},
      	{ value: TestScript, name: 'TestScript'},
      	{ value: ValueSet, name: 'ValueSet'},
      	{ value: VerificationResult, name: 'VerificationResult'},
      	{ value: VisionPrescription, name: 'VisionPrescription'}
      ],
    }
  })
  protected contained?: ResourceList[];

  /**
   * May be used to represent additional information that is not part of the basic definition of the
   * resource. To make the use of extensions safe and manageable, there is a strict set of governance
   * applied to the definition and use of extensions. Though any implementer can define an extension,
   * there is a set of requirements that SHALL be met as part of the definition of the extension.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Extension)
  protected extension?: Extension[];

  /**
   * May be used to represent additional information that is not part of the basic definition of the
   * resource and that modifies the understanding of the element that contains it and/or the
   * understanding of the containing element's descendants. Usually modifier elements provide negation
   * or qualification. To make the use of extensions safe and manageable, there is a strict set of
   * governance applied to the definition and use of extensions. Though any implementer is allowed to
   * define an extension, there is a set of requirements that SHALL be met as part of the definition of
   * the extension. Applications processing a resource are required to check for modifier extensions.
   * 
   * Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource
   * (including cannot change the meaning of modifierExtension itself).
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Extension)
  protected modifierExtension?: Extension[];

  /**
   * A concept that may be defined by a formal reference to a terminology or ontology or may be provided
   * by text.
   */
  @Type(() => CodeableConcept)
   code?: CodeableConcept;

  /**
   * A string which has at least one character and no leading or trailing whitespace and where there is
   * no whitespace other than single spaces in the contents
   * Field access restricted because there are specific valid values.
   */
  protected status?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _status?: Element;

  /**
   * A reference from one resource to another.
   */
  @Type(() => Reference)
   manufacturer?: Reference;

  /**
   * A concept that may be defined by a formal reference to a terminology or ontology or may be provided
   * by text.
   */
  @Type(() => CodeableConcept)
   doseForm?: CodeableConcept;

  /**
   * A measured amount (or an amount that can potentially be measured). Note that measured amounts
   * include amounts that are not precisely quantified, including amounts involving arbitrary units and
   * floating currencies.
   */
  @Type(() => Quantity)
   amount?: Quantity;

  /**
   * Additional names for a medication, for example, the name(s) given to a medication in different
   * countries.  For example, acetaminophen and paracetamol or salbutamol and albuterol.
   * Field access restricted because there are specific valid values.
   */
  protected synonym?: string[];

  /**
   * Extensions for synonym
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Element)
  protected _synonym?: Element[];

  /**
   * Associated or related knowledge about a medication.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => MedicationKnowledgeRelatedMedicationKnowledge)
  protected relatedMedicationKnowledge?: MedicationKnowledgeRelatedMedicationKnowledge[];

  /**
   * Associated or related medications.  For example, if the medication is a branded product (e.g.
   * Crestor), this is the Therapeutic Moeity (e.g. Rosuvastatin) or if this is a generic medication
   * (e.g. Rosuvastatin), this would link to a branded product (e.g. Crestor).
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Reference)
  protected associatedMedication?: Reference[];

  /**
   * Category of the medication or product (e.g. branded product, therapeutic moeity, generic product,
   * innovator product, etc.).
   * Field access restricted because there are specific valid values.
   */
  @Type(() => CodeableConcept)
  protected productType?: CodeableConcept[];

  /**
   * Associated documentation about the medication.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => MedicationKnowledgeMonograph)
  protected monograph?: MedicationKnowledgeMonograph[];

  /**
   * Identifies a particular constituent of interest in the product.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => MedicationKnowledgeIngredient)
  protected ingredient?: MedicationKnowledgeIngredient[];

  /**
   * A string that may contain Github Flavored Markdown syntax for optional processing by a mark down
   * presentation engine
   * Field access restricted because there are specific valid values.
   */
  protected preparationInstruction?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _preparationInstruction?: Element;

  /**
   * The intended or approved route of administration.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => CodeableConcept)
  protected intendedRoute?: CodeableConcept[];

  /**
   * The price of the medication.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => MedicationKnowledgeCost)
  protected cost?: MedicationKnowledgeCost[];

  /**
   * The program under which the medication is reviewed.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => MedicationKnowledgeMonitoringProgram)
  protected monitoringProgram?: MedicationKnowledgeMonitoringProgram[];

  /**
   * Guidelines for the administration of the medication.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => MedicationKnowledgeAdministrationGuidelines)
  protected administrationGuidelines?: MedicationKnowledgeAdministrationGuidelines[];

  /**
   * Categorization of the medication within a formulary or classification system.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => MedicationKnowledgeMedicineClassification)
  protected medicineClassification?: MedicationKnowledgeMedicineClassification[];

  /**
   * Information about a medication that is used to support knowledge.
   */
  @Type(() => MedicationKnowledgePackaging)
   packaging?: MedicationKnowledgePackaging;

  /**
   * Specifies descriptive properties of the medicine, such as color, shape, imprints, etc.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => MedicationKnowledgeDrugCharacteristic)
  protected drugCharacteristic?: MedicationKnowledgeDrugCharacteristic[];

  /**
   * Potential clinical issue with or between medication(s) (for example, drug-drug interaction,
   * drug-disease contraindication, drug-allergy interaction, etc.).
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Reference)
  protected contraindication?: Reference[];

  /**
   * Regulatory information about a medication.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => MedicationKnowledgeRegulatory)
  protected regulatory?: MedicationKnowledgeRegulatory[];

  /**
   * The time course of drug absorption, distribution, metabolism and excretion of a medication from the
   * body.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => MedicationKnowledgeKinetics)
  protected kinetics?: MedicationKnowledgeKinetics[];


  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setId(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.id) !== 'undefined') {
         delete this.id;
      }
      return;
    }
    
    if (REGEX_ID_000.test(newValue)) {
      this.id = newValue
    } else {
      throw new Error("Invalid value pattern for id of " + newValue);
    }
  }
  
  public getIdPattern(): string {
    return REGEX_ID_000.source;
  }
  
  /**
  * Gets the current value of field id.
  * @returns the value  or undefined
  */
  public getId(): string | undefined {
      return this.id;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setImplicitRules(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.implicitRules) !== 'undefined') {
         delete this.implicitRules;
      }
      return;
    }
    
    if (REGEX_IMPLICITRULES.test(newValue)) {
      this.implicitRules = newValue
    } else {
      throw new Error("Invalid value pattern for implicitRules of " + newValue);
    }
  }
  
  public getImplicitRulesPattern(): string {
    return REGEX_IMPLICITRULES.source;
  }
  
  /**
  * Gets the current value of field implicitRules.
  * @returns the value  or undefined
  */
  public getImplicitRules(): string | undefined {
      return this.implicitRules;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setLanguage(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.language) !== 'undefined') {
         delete this.language;
      }
      return;
    }
    
    if (REGEX_LANGUAGE.test(newValue)) {
      this.language = newValue
    } else {
      throw new Error("Invalid value pattern for language of " + newValue);
    }
  }
  
  public getLanguagePattern(): string {
    return REGEX_LANGUAGE.source;
  }
  
  /**
  * Gets the current value of field language.
  * @returns the value  or undefined
  */
  public getLanguage(): string | undefined {
      return this.language;
  }

  public addContained(newValue: ResourceList) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.contained) !== 'undefined') {
         delete this.contained;
      }
      return;
    }
    
    if (typeof(this.contained) === 'undefined') {
      this.contained =  [];
    }
    this.contained.push(newValue);
  }
  /**
  * Removes all elements from the array contained, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteContainedAll(): ResourceList[] {
    if (typeof(this.contained) !== 'undefined') {
       const oldArray = this.contained;
       delete this.contained;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array contained, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteContainedBySplice(start: number, deleteCount?: number): ResourceList[] {
    if (typeof(this.contained) !== 'undefined') {
       return this.contained.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field contained.
  * @returns the value  or undefined
  */
  public getContained(): ResourceList[] | undefined {
      return this.contained;
  }

  public addExtension(newValue: Extension) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.extension) !== 'undefined') {
         delete this.extension;
      }
      return;
    }
    
    if (typeof(this.extension) === 'undefined') {
      this.extension =  [];
    }
    this.extension.push(newValue);
  }
  /**
  * Removes all elements from the array extension, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteExtensionAll(): Extension[] {
    if (typeof(this.extension) !== 'undefined') {
       const oldArray = this.extension;
       delete this.extension;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array extension, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteExtensionBySplice(start: number, deleteCount?: number): Extension[] {
    if (typeof(this.extension) !== 'undefined') {
       return this.extension.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field extension.
  * @returns the value  or undefined
  */
  public getExtension(): Extension[] | undefined {
      return this.extension;
  }

  public addModifierExtension(newValue: Extension) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.modifierExtension) !== 'undefined') {
         delete this.modifierExtension;
      }
      return;
    }
    
    if (typeof(this.modifierExtension) === 'undefined') {
      this.modifierExtension =  [];
    }
    this.modifierExtension.push(newValue);
  }
  /**
  * Removes all elements from the array modifierExtension, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteModifierExtensionAll(): Extension[] {
    if (typeof(this.modifierExtension) !== 'undefined') {
       const oldArray = this.modifierExtension;
       delete this.modifierExtension;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array modifierExtension, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteModifierExtensionBySplice(start: number, deleteCount?: number): Extension[] {
    if (typeof(this.modifierExtension) !== 'undefined') {
       return this.modifierExtension.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field modifierExtension.
  * @returns the value  or undefined
  */
  public getModifierExtension(): Extension[] | undefined {
      return this.modifierExtension;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setStatus(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.status) !== 'undefined') {
         delete this.status;
      }
      return;
    }
    
    if (REGEX_STATUS_000.test(newValue)) {
      this.status = newValue
    } else {
      throw new Error("Invalid value pattern for status of " + newValue);
    }
  }
  
  public getStatusPattern(): string {
    return REGEX_STATUS_000.source;
  }
  
  /**
  * Gets the current value of field status.
  * @returns the value  or undefined
  */
  public getStatus(): string | undefined {
      return this.status;
  }

  public addSynonym(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.synonym) !== 'undefined') {
         delete this.synonym;
      }
      return;
    }
    
    if (typeof(this.synonym) === 'undefined') {
      this.synonym =  [];
    }
    this.synonym.push(newValue);
  }
  /**
  * Removes all elements from the array synonym, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteSynonymAll(): string[] {
    if (typeof(this.synonym) !== 'undefined') {
       const oldArray = this.synonym;
       delete this.synonym;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array synonym, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteSynonymBySplice(start: number, deleteCount?: number): string[] {
    if (typeof(this.synonym) !== 'undefined') {
       return this.synonym.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field synonym.
  * @returns the value  or undefined
  */
  public getSynonym(): string[] | undefined {
      return this.synonym;
  }

  public add_synonym(newValue: Element) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this._synonym) !== 'undefined') {
         delete this._synonym;
      }
      return;
    }
    
    if (typeof(this._synonym) === 'undefined') {
      this._synonym =  [];
    }
    this._synonym.push(newValue);
  }
  /**
  * Removes all elements from the array _synonym, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public delete_synonymAll(): Element[] {
    if (typeof(this._synonym) !== 'undefined') {
       const oldArray = this._synonym;
       delete this._synonym;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array _synonym, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public delete_synonymBySplice(start: number, deleteCount?: number): Element[] {
    if (typeof(this._synonym) !== 'undefined') {
       return this._synonym.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field _synonym.
  * @returns the value  or undefined
  */
  public get_synonym(): Element[] | undefined {
      return this._synonym;
  }

  public addRelatedMedicationKnowledge(newValue: MedicationKnowledgeRelatedMedicationKnowledge) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.relatedMedicationKnowledge) !== 'undefined') {
         delete this.relatedMedicationKnowledge;
      }
      return;
    }
    
    if (typeof(this.relatedMedicationKnowledge) === 'undefined') {
      this.relatedMedicationKnowledge =  [];
    }
    this.relatedMedicationKnowledge.push(newValue);
  }
  /**
  * Removes all elements from the array relatedMedicationKnowledge, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteRelatedMedicationKnowledgeAll(): MedicationKnowledgeRelatedMedicationKnowledge[] {
    if (typeof(this.relatedMedicationKnowledge) !== 'undefined') {
       const oldArray = this.relatedMedicationKnowledge;
       delete this.relatedMedicationKnowledge;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array relatedMedicationKnowledge, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteRelatedMedicationKnowledgeBySplice(start: number, deleteCount?: number): MedicationKnowledgeRelatedMedicationKnowledge[] {
    if (typeof(this.relatedMedicationKnowledge) !== 'undefined') {
       return this.relatedMedicationKnowledge.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field relatedMedicationKnowledge.
  * @returns the value  or undefined
  */
  public getRelatedMedicationKnowledge(): MedicationKnowledgeRelatedMedicationKnowledge[] | undefined {
      return this.relatedMedicationKnowledge;
  }

  public addAssociatedMedication(newValue: Reference) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.associatedMedication) !== 'undefined') {
         delete this.associatedMedication;
      }
      return;
    }
    
    if (typeof(this.associatedMedication) === 'undefined') {
      this.associatedMedication =  [];
    }
    this.associatedMedication.push(newValue);
  }
  /**
  * Removes all elements from the array associatedMedication, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteAssociatedMedicationAll(): Reference[] {
    if (typeof(this.associatedMedication) !== 'undefined') {
       const oldArray = this.associatedMedication;
       delete this.associatedMedication;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array associatedMedication, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteAssociatedMedicationBySplice(start: number, deleteCount?: number): Reference[] {
    if (typeof(this.associatedMedication) !== 'undefined') {
       return this.associatedMedication.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field associatedMedication.
  * @returns the value  or undefined
  */
  public getAssociatedMedication(): Reference[] | undefined {
      return this.associatedMedication;
  }

  public addProductType(newValue: CodeableConcept) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.productType) !== 'undefined') {
         delete this.productType;
      }
      return;
    }
    
    if (typeof(this.productType) === 'undefined') {
      this.productType =  [];
    }
    this.productType.push(newValue);
  }
  /**
  * Removes all elements from the array productType, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteProductTypeAll(): CodeableConcept[] {
    if (typeof(this.productType) !== 'undefined') {
       const oldArray = this.productType;
       delete this.productType;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array productType, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteProductTypeBySplice(start: number, deleteCount?: number): CodeableConcept[] {
    if (typeof(this.productType) !== 'undefined') {
       return this.productType.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field productType.
  * @returns the value  or undefined
  */
  public getProductType(): CodeableConcept[] | undefined {
      return this.productType;
  }

  public addMonograph(newValue: MedicationKnowledgeMonograph) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.monograph) !== 'undefined') {
         delete this.monograph;
      }
      return;
    }
    
    if (typeof(this.monograph) === 'undefined') {
      this.monograph =  [];
    }
    this.monograph.push(newValue);
  }
  /**
  * Removes all elements from the array monograph, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteMonographAll(): MedicationKnowledgeMonograph[] {
    if (typeof(this.monograph) !== 'undefined') {
       const oldArray = this.monograph;
       delete this.monograph;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array monograph, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteMonographBySplice(start: number, deleteCount?: number): MedicationKnowledgeMonograph[] {
    if (typeof(this.monograph) !== 'undefined') {
       return this.monograph.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field monograph.
  * @returns the value  or undefined
  */
  public getMonograph(): MedicationKnowledgeMonograph[] | undefined {
      return this.monograph;
  }

  public addIngredient(newValue: MedicationKnowledgeIngredient) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.ingredient) !== 'undefined') {
         delete this.ingredient;
      }
      return;
    }
    
    if (typeof(this.ingredient) === 'undefined') {
      this.ingredient =  [];
    }
    this.ingredient.push(newValue);
  }
  /**
  * Removes all elements from the array ingredient, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteIngredientAll(): MedicationKnowledgeIngredient[] {
    if (typeof(this.ingredient) !== 'undefined') {
       const oldArray = this.ingredient;
       delete this.ingredient;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array ingredient, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteIngredientBySplice(start: number, deleteCount?: number): MedicationKnowledgeIngredient[] {
    if (typeof(this.ingredient) !== 'undefined') {
       return this.ingredient.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field ingredient.
  * @returns the value  or undefined
  */
  public getIngredient(): MedicationKnowledgeIngredient[] | undefined {
      return this.ingredient;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setPreparationInstruction(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.preparationInstruction) !== 'undefined') {
         delete this.preparationInstruction;
      }
      return;
    }
    
    if (REGEX_PREPARATIONINSTRUCTION.test(newValue)) {
      this.preparationInstruction = newValue
    } else {
      throw new Error("Invalid value pattern for preparationInstruction of " + newValue);
    }
  }
  
  public getPreparationInstructionPattern(): string {
    return REGEX_PREPARATIONINSTRUCTION.source;
  }
  
  /**
  * Gets the current value of field preparationInstruction.
  * @returns the value  or undefined
  */
  public getPreparationInstruction(): string | undefined {
      return this.preparationInstruction;
  }

  public addIntendedRoute(newValue: CodeableConcept) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.intendedRoute) !== 'undefined') {
         delete this.intendedRoute;
      }
      return;
    }
    
    if (typeof(this.intendedRoute) === 'undefined') {
      this.intendedRoute =  [];
    }
    this.intendedRoute.push(newValue);
  }
  /**
  * Removes all elements from the array intendedRoute, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteIntendedRouteAll(): CodeableConcept[] {
    if (typeof(this.intendedRoute) !== 'undefined') {
       const oldArray = this.intendedRoute;
       delete this.intendedRoute;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array intendedRoute, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteIntendedRouteBySplice(start: number, deleteCount?: number): CodeableConcept[] {
    if (typeof(this.intendedRoute) !== 'undefined') {
       return this.intendedRoute.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field intendedRoute.
  * @returns the value  or undefined
  */
  public getIntendedRoute(): CodeableConcept[] | undefined {
      return this.intendedRoute;
  }

  public addCost(newValue: MedicationKnowledgeCost) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.cost) !== 'undefined') {
         delete this.cost;
      }
      return;
    }
    
    if (typeof(this.cost) === 'undefined') {
      this.cost =  [];
    }
    this.cost.push(newValue);
  }
  /**
  * Removes all elements from the array cost, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteCostAll(): MedicationKnowledgeCost[] {
    if (typeof(this.cost) !== 'undefined') {
       const oldArray = this.cost;
       delete this.cost;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array cost, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteCostBySplice(start: number, deleteCount?: number): MedicationKnowledgeCost[] {
    if (typeof(this.cost) !== 'undefined') {
       return this.cost.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field cost.
  * @returns the value  or undefined
  */
  public getCost(): MedicationKnowledgeCost[] | undefined {
      return this.cost;
  }

  public addMonitoringProgram(newValue: MedicationKnowledgeMonitoringProgram) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.monitoringProgram) !== 'undefined') {
         delete this.monitoringProgram;
      }
      return;
    }
    
    if (typeof(this.monitoringProgram) === 'undefined') {
      this.monitoringProgram =  [];
    }
    this.monitoringProgram.push(newValue);
  }
  /**
  * Removes all elements from the array monitoringProgram, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteMonitoringProgramAll(): MedicationKnowledgeMonitoringProgram[] {
    if (typeof(this.monitoringProgram) !== 'undefined') {
       const oldArray = this.monitoringProgram;
       delete this.monitoringProgram;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array monitoringProgram, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteMonitoringProgramBySplice(start: number, deleteCount?: number): MedicationKnowledgeMonitoringProgram[] {
    if (typeof(this.monitoringProgram) !== 'undefined') {
       return this.monitoringProgram.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field monitoringProgram.
  * @returns the value  or undefined
  */
  public getMonitoringProgram(): MedicationKnowledgeMonitoringProgram[] | undefined {
      return this.monitoringProgram;
  }

  public addAdministrationGuidelines(newValue: MedicationKnowledgeAdministrationGuidelines) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.administrationGuidelines) !== 'undefined') {
         delete this.administrationGuidelines;
      }
      return;
    }
    
    if (typeof(this.administrationGuidelines) === 'undefined') {
      this.administrationGuidelines =  [];
    }
    this.administrationGuidelines.push(newValue);
  }
  /**
  * Removes all elements from the array administrationGuidelines, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteAdministrationGuidelinesAll(): MedicationKnowledgeAdministrationGuidelines[] {
    if (typeof(this.administrationGuidelines) !== 'undefined') {
       const oldArray = this.administrationGuidelines;
       delete this.administrationGuidelines;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array administrationGuidelines, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteAdministrationGuidelinesBySplice(start: number, deleteCount?: number): MedicationKnowledgeAdministrationGuidelines[] {
    if (typeof(this.administrationGuidelines) !== 'undefined') {
       return this.administrationGuidelines.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field administrationGuidelines.
  * @returns the value  or undefined
  */
  public getAdministrationGuidelines(): MedicationKnowledgeAdministrationGuidelines[] | undefined {
      return this.administrationGuidelines;
  }

  public addMedicineClassification(newValue: MedicationKnowledgeMedicineClassification) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.medicineClassification) !== 'undefined') {
         delete this.medicineClassification;
      }
      return;
    }
    
    if (typeof(this.medicineClassification) === 'undefined') {
      this.medicineClassification =  [];
    }
    this.medicineClassification.push(newValue);
  }
  /**
  * Removes all elements from the array medicineClassification, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteMedicineClassificationAll(): MedicationKnowledgeMedicineClassification[] {
    if (typeof(this.medicineClassification) !== 'undefined') {
       const oldArray = this.medicineClassification;
       delete this.medicineClassification;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array medicineClassification, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteMedicineClassificationBySplice(start: number, deleteCount?: number): MedicationKnowledgeMedicineClassification[] {
    if (typeof(this.medicineClassification) !== 'undefined') {
       return this.medicineClassification.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field medicineClassification.
  * @returns the value  or undefined
  */
  public getMedicineClassification(): MedicationKnowledgeMedicineClassification[] | undefined {
      return this.medicineClassification;
  }

  public addDrugCharacteristic(newValue: MedicationKnowledgeDrugCharacteristic) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.drugCharacteristic) !== 'undefined') {
         delete this.drugCharacteristic;
      }
      return;
    }
    
    if (typeof(this.drugCharacteristic) === 'undefined') {
      this.drugCharacteristic =  [];
    }
    this.drugCharacteristic.push(newValue);
  }
  /**
  * Removes all elements from the array drugCharacteristic, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteDrugCharacteristicAll(): MedicationKnowledgeDrugCharacteristic[] {
    if (typeof(this.drugCharacteristic) !== 'undefined') {
       const oldArray = this.drugCharacteristic;
       delete this.drugCharacteristic;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array drugCharacteristic, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteDrugCharacteristicBySplice(start: number, deleteCount?: number): MedicationKnowledgeDrugCharacteristic[] {
    if (typeof(this.drugCharacteristic) !== 'undefined') {
       return this.drugCharacteristic.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field drugCharacteristic.
  * @returns the value  or undefined
  */
  public getDrugCharacteristic(): MedicationKnowledgeDrugCharacteristic[] | undefined {
      return this.drugCharacteristic;
  }

  public addContraindication(newValue: Reference) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.contraindication) !== 'undefined') {
         delete this.contraindication;
      }
      return;
    }
    
    if (typeof(this.contraindication) === 'undefined') {
      this.contraindication =  [];
    }
    this.contraindication.push(newValue);
  }
  /**
  * Removes all elements from the array contraindication, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteContraindicationAll(): Reference[] {
    if (typeof(this.contraindication) !== 'undefined') {
       const oldArray = this.contraindication;
       delete this.contraindication;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array contraindication, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteContraindicationBySplice(start: number, deleteCount?: number): Reference[] {
    if (typeof(this.contraindication) !== 'undefined') {
       return this.contraindication.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field contraindication.
  * @returns the value  or undefined
  */
  public getContraindication(): Reference[] | undefined {
      return this.contraindication;
  }

  public addRegulatory(newValue: MedicationKnowledgeRegulatory) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.regulatory) !== 'undefined') {
         delete this.regulatory;
      }
      return;
    }
    
    if (typeof(this.regulatory) === 'undefined') {
      this.regulatory =  [];
    }
    this.regulatory.push(newValue);
  }
  /**
  * Removes all elements from the array regulatory, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteRegulatoryAll(): MedicationKnowledgeRegulatory[] {
    if (typeof(this.regulatory) !== 'undefined') {
       const oldArray = this.regulatory;
       delete this.regulatory;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array regulatory, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteRegulatoryBySplice(start: number, deleteCount?: number): MedicationKnowledgeRegulatory[] {
    if (typeof(this.regulatory) !== 'undefined') {
       return this.regulatory.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field regulatory.
  * @returns the value  or undefined
  */
  public getRegulatory(): MedicationKnowledgeRegulatory[] | undefined {
      return this.regulatory;
  }

  public addKinetics(newValue: MedicationKnowledgeKinetics) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.kinetics) !== 'undefined') {
         delete this.kinetics;
      }
      return;
    }
    
    if (typeof(this.kinetics) === 'undefined') {
      this.kinetics =  [];
    }
    this.kinetics.push(newValue);
  }
  /**
  * Removes all elements from the array kinetics, returning the deleted elements.
  * @returns An array containing the elements that were deleted.
  */
  public deleteKineticsAll(): MedicationKnowledgeKinetics[] {
    if (typeof(this.kinetics) !== 'undefined') {
       const oldArray = this.kinetics;
       delete this.kinetics;
       return oldArray;
    }
    return [];
  }
  
  /**
  * Removes elements from the array kinetics, returning the deleted elements.
  * @param start The zero-based location in the array from which to start removing elements.
  * @param deleteCount The number of elements to remove.
  * @returns An array containing the elements that were deleted, or an empty array if the element
  *     was undefined.
  */
  public deleteKineticsBySplice(start: number, deleteCount?: number): MedicationKnowledgeKinetics[] {
    if (typeof(this.kinetics) !== 'undefined') {
       return this.kinetics.splice(start, deleteCount);
    }
    return [];
  }
  
  /**
  * Gets the current value of field kinetics.
  * @returns the value  or undefined
  */
  public getKinetics(): MedicationKnowledgeKinetics[] | undefined {
      return this.kinetics;
  }


}


