import { getValidValueIdx } from '../FhirTsLibValidation/FhirUtils';
import { Type } from 'class-transformer';
import { REGEX_ID, REGEX_PROPERTY_000, REGEX_VALUE } from '../FhirTsLibValidation/FhirRegex';
import { Element, Extension } from './FhirType';
import { ValueSetFilterOp_list_ValidValues } from '../FhirTsLibValidation/Fhir_ValidValues';



/**
 * A ValueSet resource instance specifies a set of codes drawn from one or more code systems, intended
 * for use in a particular context. Value sets link between [[[CodeSystem]]] definitions and their use
 * in [coded elements](terminologies.html).
 *
 * Generated by Gallaware, Inc. from:
 *    file:/Users/admin/Documents/DevNetbeans/jsonSchemaToJava/target/classes/schema/fhir.schema.json#/definitions/ValueSet_Filter
 */
export class ValueSetFilter {
  /**
   * A sequence of Unicode characters
   * Field access restricted because there are specific valid values.
   */
  protected id?: string;

  /**
   * May be used to represent additional information that is not part of the basic definition of the
   * element. To make the use of extensions safe and manageable, there is a strict set of governance
   * applied to the definition and use of extensions. Though any implementer can define an extension,
   * there is a set of requirements that SHALL be met as part of the definition of the extension.
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Extension)
  protected extension?: Extension[];

  /**
   * May be used to represent additional information that is not part of the basic definition of the
   * element and that modifies the understanding of the element in which it is contained and/or the
   * understanding of the containing element's descendants. Usually modifier elements provide negation
   * or qualification. To make the use of extensions safe and manageable, there is a strict set of
   * governance applied to the definition and use of extensions. Though any implementer can define an
   * extension, there is a set of requirements that SHALL be met as part of the definition of the
   * extension. Applications processing a resource are required to check for modifier extensions.
   * 
   * Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource
   * (including cannot change the meaning of modifierExtension itself).
   * Field access restricted because there are specific valid values.
   */
  @Type(() => Extension)
  protected modifierExtension?: Extension[];

  /**
   * A string which has at least one character and no leading or trailing whitespace and where there is
   * no whitespace other than single spaces in the contents
   * Field access restricted because there are specific valid values.
   */
  protected property?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _property?: Element;

  /**
   * The kind of operation to perform as a part of the filter criteria.
   * Field access restricted because there are specific valid values.
   */
  protected op?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _op?: Element;

  /**
   * A sequence of Unicode characters
   * Field access restricted because there are specific valid values.
   */
  protected value?: string;

  /**
   * Base definition for all elements in a resource.
   */
  @Type(() => Element)
   _value?: Element;


  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setId(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.id) !== 'undefined') {
         delete this.id;
      }
      return;
    }
    
    if (REGEX_ID.test(newValue)) {
      this.id = newValue
    } else {
      throw new Error("Invalid value pattern for id of " + newValue);
    }
  }
  
  public getIdPattern(): string {
    return REGEX_ID.source;
  }
  

  public getId(): string | undefined {
      return this.id;
  }

  public addExtension(newValue: Extension) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.extension) !== 'undefined') {
         delete this.extension;
      }
      return;
    }
    
    if (typeof(this.extension) === 'undefined') {
      this.extension =  [];
    }
    this.extension.push(newValue);
  }

  public getExtension(): Extension[] | undefined {
      return this.extension;
  }

  public addModifierExtension(newValue: Extension) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.modifierExtension) !== 'undefined') {
         delete this.modifierExtension;
      }
      return;
    }
    
    if (typeof(this.modifierExtension) === 'undefined') {
      this.modifierExtension =  [];
    }
    this.modifierExtension.push(newValue);
  }

  public getModifierExtension(): Extension[] | undefined {
      return this.modifierExtension;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setProperty(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.property) !== 'undefined') {
         delete this.property;
      }
      return;
    }
    
    if (REGEX_PROPERTY_000.test(newValue)) {
      this.property = newValue
    } else {
      throw new Error("Invalid value pattern for property of " + newValue);
    }
  }
  
  public getPropertyPattern(): string {
    return REGEX_PROPERTY_000.source;
  }
  

  public getProperty(): string | undefined {
      return this.property;
  }

  /*
  * This sets the data ensuring that the value is valid.  If not valid, it throws an error
  * that should be caught.
  */
  public setOp(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.op) !== 'undefined') {
         delete this.op;
      }
      return;
    }
    
    const idx = getValidValueIdx(ValueSetFilterOp_list_ValidValues, newValue);
    if (idx >= 0) {
      this.op = ValueSetFilterOp_list_ValidValues[idx];
    } else {
      throw new Error("Unknown op of " + newValue);
    }
  }
  
  public getValueSetFilterOpValidValues(): string[] {
    return ValueSetFilterOp_list_ValidValues;
  }
  

  public getOp(): string | undefined {
      return this.op;
  }

  /*
  * This sets the data ensuring that the value is valid pattern.  If not valid, it throws an error
  * that should be caught.
  */
  public setValue(newValue: string) {
    if (typeof(newValue) === 'undefined') {
      if (typeof(this.value) !== 'undefined') {
         delete this.value;
      }
      return;
    }
    
    if (REGEX_VALUE.test(newValue)) {
      this.value = newValue
    } else {
      throw new Error("Invalid value pattern for value of " + newValue);
    }
  }
  
  public getValuePattern(): string {
    return REGEX_VALUE.source;
  }
  

  public getValue(): string | undefined {
      return this.value;
  }


}


